/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.Form;

import java.sql.Connection;
import java.sql.Statement;
import java.util.Vector;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static qlks.Form.DangNhap_Form.Hostname;
import static qlks.Form.DangNhap_Form.Password;
import static qlks.Form.DangNhap_Form.Port;
import static qlks.Form.DangNhap_Form.SID;
import static qlks.Form.DangNhap_Form.Username;
import static qlks.MyConnection.getConnection;
/**
 *
 * @author Dell
 */
public class HeThong4 extends javax.swing.JFrame {

    /**
     * Creates new form HeThong4
     */
    public HeThong4() {
        initComponents();
    }

    Connection con = null;
    Statement st = null;
    Vector title = new Vector();
    Vector data = new Vector();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        thoat4 = new javax.swing.JButton();
        btn_controlfile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        object_schema = new javax.swing.JTextField();
        object_name = new javax.swing.JTextField();
        policy_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_controlfile1 = new javax.swing.JButton();
        btn_controlfile2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Quản Lí Người Dùng"));

        thoat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/THOAT.png"))); // NOI18N
        thoat4.setText("Thoát");
        thoat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoat4ActionPerformed(evt);
            }
        });

        btn_controlfile.setText("Tạo Policy");
        btn_controlfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_controlfileActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        object_schema.setText("hr");

        jLabel1.setText("object_schema");

        jLabel2.setText("object_name");

        jLabel3.setText("policy_name");

        btn_controlfile1.setText("Disable Policy");
        btn_controlfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_controlfile1ActionPerformed(evt);
            }
        });

        btn_controlfile2.setText("Enable Policy");
        btn_controlfile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_controlfile2ActionPerformed(evt);
            }
        });

        jButton1.setText("xem policy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("kiểm soát user");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa Policy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_controlfile)
                        .addGap(18, 18, 18)
                        .addComponent(btn_controlfile1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_controlfile2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thoat4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(policy_name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(object_name)
                            .addComponent(object_schema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                        .addGap(258, 258, 258)
                        .addComponent(jButton1)
                        .addGap(46, 46, 46)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(object_schema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(object_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(policy_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_controlfile)
                            .addComponent(btn_controlfile1)
                            .addComponent(btn_controlfile2)
                            .addComponent(jButton3))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thoat4)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Boolean ktrauser() {
        if ((object_schema.getText().equals("hr") || object_schema.getText().equals("scott")) || (object_name.getText().equals("CTHOADON")
                || object_name.getText().equals("HOADON") || object_name.getText().equals("PHONG") || object_name.getText().equals("DICHVU")
                || object_name.getText().equals("KHACHHANG") || object_name.getText().equals("THUEPHONG"))) {
            return true;
        }
        return false;
    }

    public Boolean ktraobject() {
        if (object_name.getText().equals("CTHOADON")
                || object_name.getText().equals("HOADON") || object_name.getText().equals("PHONG") || object_name.getText().equals("DICHVU")
                || object_name.getText().equals("KHACHHANG") || object_name.getText().equals("THUEPHONG")||
                object_name.getText().equals("cthoadon")
                || object_name.getText().equals("hoadon") || object_name.getText().equals("phong") || object_name.getText().equals("dichvu")
                || object_name.getText().equals("khachhang") || object_name.getText().equals("thuephong")) {
            return true;
        }
        return false;
    }
    public Boolean ktratxt()
    {
        if(object_schema.getText().equals("")||object_name.getText().equals("")||policy_name.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Nhập đầy đủ thông tin!");
            return false;}
        else
        { 
            return true;}
    }
    private void btn_controlfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_controlfileActionPerformed
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        if(ktratxt()&&ktrauser()&&ktraobject())
        {
        try {
            st = (Statement) con.createStatement();
            String sql = "begin\n"
                    + "   dbms_fga.add_policy\n"
                    + "   (\n"
                    + "     object_schema => '"+object_schema.getText()+"',\n"
                    + "     object_name => '"+object_name.getText()+"',\n"
                    + "     policy_name =>'"+policy_name.getText()+"',\n"
                    + "     statement_types => 'select,insert,delete,update');\n"
                    + "end;";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            //ex.printStackTrace();

        }
        }
        else{JOptionPane.showMessageDialog(rootPane, "Thất Bại!");}
    }//GEN-LAST:event_btn_controlfileActionPerformed

    private void btn_controlfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_controlfile1ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        if(ktratxt()&&ktrauser()&&ktraobject())
        {
        try {
            st = (Statement) con.createStatement();
            String sql = "begin\n"
                    + "   dbms_fga.disable_policy\n"
                    + "   (\n"
                    + "     object_schema => '"+object_schema.getText()+"',\n"
                    + "     object_name => '"+object_name.getText()+"',\n"
                    + "     policy_name =>'"+policy_name.getText()+"'"
                    + ");\n"
                    + "end;";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            //ex.printStackTrace();

        }
        }
        else{JOptionPane.showMessageDialog(rootPane, "Thất Bại!");}
    }//GEN-LAST:event_btn_controlfile1ActionPerformed

    private void btn_controlfile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_controlfile2ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        if(ktratxt()&&ktrauser()&&ktraobject())
        {
        try {
            st = (Statement) con.createStatement();
            String sql = "begin\n"
                    + "   dbms_fga.enable_policy\n"
                    + "   (\n"
                    + "     object_schema => '"+object_schema.getText()+"',\n"
                    + "     object_name => '"+object_name.getText()+"',\n"
                    + "     policy_name =>'"+policy_name.getText()+"'"
                    + ");\n"
                    + "end;";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            //ex.printStackTrace();

        }
        }
        else{JOptionPane.showMessageDialog(rootPane, "Thất Bại!");}
    }//GEN-LAST:event_btn_controlfile2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        title.clear();
        data.clear();
        title.add("OBJECT_SCHEMA");
        title.add("OBJECT_NAME");
        title.add("POLICY_OWNER");
        title.add("POLICY_NAME");
        title.add("ENABLED");
        title.add("SEL");
        title.add("INS");
        title.add("UPD");
        title.add("DEL");
        title.add("AUDIT_TRAIL");
        title.add("POLICY_COLUMN_OPTIONS");
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "select * from dba_audit_policies";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(10));
                v.add(rs.getString(11));
                v.add(rs.getString(12));
                v.add(rs.getString(13));
                v.add(rs.getString(14));
                v.add(rs.getString(15));
                v.add(rs.getString(16));
                data.add(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }

        jTable1.setModel(new DefaultTableModel(data, title));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        if(ktratxt()&&ktrauser()&&ktraobject())
        {
        try {
            st = (Statement) con.createStatement();
            String sql = "begin\n"
                    + "   dbms_fga.drop_policy\n"
                    + "   (\n"
                    + "     object_schema => '"+object_schema.getText()+"',\n"
                    + "     object_name => '"+object_name.getText()+"',\n"
                    + "     policy_name =>'"+policy_name.getText()+"'"
                    + ");\n"
                    + "end;";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            //ex.printStackTrace();

        }
        }
        else{JOptionPane.showMessageDialog(rootPane, "Thất Bại!");}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        title.clear();
        data.clear();
        title.add("SESSION_ID");
        title.add("TIMESTAMP");
        title.add("DB_USER");
        title.add("OS_USER");
        title.add("USERHOST");
        title.add("OBJECT_SCHEMA");
        title.add("OBJECT_NAME");
        title.add("POLICY_NAME");
        title.add("SCN");
        title.add("SQL_TEXT");
        title.add("STATEMENT_TYPE");
        title.add("EXTENDED_TIMESTAMP");
        title.add("INSTANCE_NUMBER");
        title.add("OS_PROCESS");
        title.add("TRANSACTIONID");
        title.add("STATEMENTID");
        title.add("ENTRYID");
        title.add("DBID");
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "select * from dba_fga_audit_trail";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(9));
                v.add(rs.getString(10));
                v.add(rs.getString(11));
                v.add(rs.getString(12));
                v.add(rs.getString(13));
                v.add(rs.getString(16));
                v.add(rs.getString(17));
                v.add(rs.getString(20));
                v.add(rs.getString(21));
                v.add(rs.getString(22));
                v.add(rs.getString(23));
                v.add(rs.getString(24));
                v.add(rs.getString(26));
                data.add(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }

        jTable1.setModel(new DefaultTableModel(data, title));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void thoat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoat4ActionPerformed
        // TODO add your handling code here:
        thoat4.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát chương"
            + " trình không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_thoat4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeThong4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeThong4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeThong4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeThong4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeThong4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_controlfile;
    private javax.swing.JButton btn_controlfile1;
    private javax.swing.JButton btn_controlfile2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField object_name;
    private javax.swing.JTextField object_schema;
    private javax.swing.JTextField policy_name;
    private javax.swing.JButton thoat4;
    // End of variables declaration//GEN-END:variables
}
