/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.Form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import qlks.CapQuyenDoiTuong;
import static qlks.MyConnection.getConnection;
import qlks.audit;
import static qlks.Form.DangNhap_Form.Hostname;
import static qlks.Form.DangNhap_Form.Password;
import static qlks.Form.DangNhap_Form.Port;
import static qlks.Form.DangNhap_Form.SID;
import static qlks.Form.DangNhap_Form.Username;

/**
 *
 * @author Hieu
 */
public class HeThong2 extends javax.swing.JFrame {

    /**
     * Creates new form chucnang2
     */
    public HeThong2() {
        initComponents();
        rd_tbs1.setEnabled(false);
        rd_tbs2.setEnabled(false);
        rd_tbs3.setEnabled(false);
        rd_tbs4.setEnabled(false);
        rd_mb.setSelected(true);
        setLocationRelativeTo(null);
        txt_thamso.setEnabled(false);

    }
    Connection con = null;
    Statement st = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        txt_matkhau = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txt_quota = new javax.swing.JTextField();
        rd_mb = new javax.swing.JRadioButton();
        rd_kb = new javax.swing.JRadioButton();
        rd_gb = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        rd_ktramk = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        rd_tbs1 = new javax.swing.JRadioButton();
        rd_tbs2 = new javax.swing.JRadioButton();
        rd_tbs3 = new javax.swing.JRadioButton();
        rd_tbs4 = new javax.swing.JRadioButton();
        btn_tao = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_themTablespace = new javax.swing.JButton();
        btn_xoaTablespace = new javax.swing.JButton();
        jRadioButton_con = new javax.swing.JRadioButton();
        jRadioButton_mat = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txt_Tablespace = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_datafile = new javax.swing.JTextField();
        txt_ten1 = new javax.swing.JTextField();
        btn_themDatafile = new javax.swing.JButton();
        btn_xoaDatafile = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_size = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_tenuser = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btn_capquyen = new javax.swing.JButton();
        btn_thuhoiquyen = new javax.swing.JButton();
        rd_createprocedure = new javax.swing.JRadioButton();
        rd_createsession = new javax.swing.JRadioButton();
        rd_createtable = new javax.swing.JRadioButton();
        rd_createtrigger = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        btn_capquyen2 = new javax.swing.JButton();
        btn_thuhoiquyen2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_tennhomquyen = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        rd_createsession1 = new javax.swing.JRadioButton();
        rd_createtable1 = new javax.swing.JRadioButton();
        rd_createprocedure1 = new javax.swing.JRadioButton();
        rd_createuser = new javax.swing.JRadioButton();
        btn_thuhoiquyen1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_tennhomquyen1 = new javax.swing.JTextField();
        btn_taorole = new javax.swing.JButton();
        btn_xoarole = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        txt_tenprofile = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_suaprofile = new javax.swing.JButton();
        btn_xoaprofile = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_giatri_FAILED_LOGIN_ATTEMPTS = new javax.swing.JTextField();
        btn_taoprofile = new javax.swing.JButton();
        FAILED_LOGIN_ATTEMPTS = new javax.swing.JCheckBox();
        PASSWORD_LIFE_TIME = new javax.swing.JCheckBox();
        PASSWORD_REUSE_TIME = new javax.swing.JCheckBox();
        PASSWORD_REUSE_MAX = new javax.swing.JCheckBox();
        PASSWORD_GRACE_TIME = new javax.swing.JCheckBox();
        txt_giatri_PASSWORD_LIFE_TIME = new javax.swing.JTextField();
        txt_giatri_PASSWORD_REUSE_TIME = new javax.swing.JTextField();
        txt_giatri_PASSWORD_REUSE_MAX = new javax.swing.JTextField();
        txt_giatri_PASSWORD_GRACE_TIME = new javax.swing.JTextField();
        txt_thamso = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        thoat4 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Tạo User"));

        jLabel1.setText("Tên: ");

        jLabel2.setText("Mật khẩu:");

        txt_matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matkhauActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Quota"));

        buttonGroup1.add(rd_mb);
        rd_mb.setText("MB");

        buttonGroup1.add(rd_kb);
        rd_kb.setText("KB");

        buttonGroup1.add(rd_gb);
        rd_gb.setText("GB");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_quota)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd_gb)
                    .addComponent(rd_mb)
                    .addComponent(rd_kb))
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_quota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rd_mb)
                        .addGap(10, 10, 10)
                        .addComponent(rd_kb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(rd_gb)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Profile"));

        rd_ktramk.setText("KiemTraMatKhau");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rd_ktramk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(rd_ktramk)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tablespace"));

        buttonGroup2.add(rd_tbs1);
        rd_tbs1.setText("tbs1");

        buttonGroup2.add(rd_tbs2);
        rd_tbs2.setText("tbs2");

        buttonGroup2.add(rd_tbs3);
        rd_tbs3.setText("tbs3");

        buttonGroup2.add(rd_tbs4);
        rd_tbs4.setText("tbs4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd_tbs1)
                    .addComponent(rd_tbs2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd_tbs3)
                    .addComponent(rd_tbs4))
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_tbs1)
                    .addComponent(rd_tbs3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_tbs4)
                    .addComponent(rd_tbs2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btn_tao.setText("Tạo");
        btn_tao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taoActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btn_tao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_sua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_xoa))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_matkhau)
                                    .addComponent(txt_ten)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tao)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa)
                    .addComponent(jButton1))
                .addGap(24, 24, 24))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thêm/Xóa Tablespace"));

        btn_themTablespace.setText("Thêm");
        btn_themTablespace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themTablespaceActionPerformed(evt);
            }
        });

        btn_xoaTablespace.setText("Xóa");
        btn_xoaTablespace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaTablespaceActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRadioButton_con);
        jRadioButton_con.setText("Còn Datafile");

        buttonGroup5.add(jRadioButton_mat);
        jRadioButton_mat.setText("Mất Datafile");

        jLabel6.setText("Tablespace:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_themTablespace)
                            .addComponent(btn_xoaTablespace))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_con)
                            .addComponent(jRadioButton_mat))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Tablespace)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Tablespace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themTablespace)
                    .addComponent(jRadioButton_con))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_xoaTablespace)
                    .addComponent(jRadioButton_mat))
                .addGap(8, 8, 8))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thêm, xóa một datafile vào một tablespace"));

        jLabel3.setText("Tablespace:");

        jLabel4.setText("Datafile:");

        txt_datafile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_datafileActionPerformed(evt);
            }
        });

        btn_themDatafile.setText("Thêm");
        btn_themDatafile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themDatafileActionPerformed(evt);
            }
        });

        btn_xoaDatafile.setText("Xóa");
        btn_xoaDatafile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaDatafileActionPerformed(evt);
            }
        });

        jLabel5.setText("Size:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_ten1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(txt_datafile)
                    .addComponent(txt_size))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_xoaDatafile, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_themDatafile, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ten1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_themDatafile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_datafile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoaDatafile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cấp quyền/ nhóm quyền và thu hồi quyền/nhóm quyền cho User"));

        jLabel7.setText("Tên User:");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Quyền đối tượng"));

        btn_capquyen.setText("Cấp");
        btn_capquyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capquyenActionPerformed(evt);
            }
        });

        btn_thuhoiquyen.setText("Thu Hồi");
        btn_thuhoiquyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thuhoiquyenActionPerformed(evt);
            }
        });

        buttonGroup3.add(rd_createprocedure);
        rd_createprocedure.setText("CREATE PROCEDURE");

        buttonGroup3.add(rd_createsession);
        rd_createsession.setText("CREATE SESSION");

        buttonGroup3.add(rd_createtable);
        rd_createtable.setText("CREATE TABLE");

        buttonGroup3.add(rd_createtrigger);
        rd_createtrigger.setText("CREATE TRIGGER");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rd_createtable)
                            .addComponent(rd_createsession))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rd_createprocedure)
                            .addComponent(rd_createtrigger))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btn_capquyen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_thuhoiquyen)
                        .addGap(57, 57, 57))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_createsession)
                    .addComponent(rd_createprocedure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_createtable)
                    .addComponent(rd_createtrigger))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_capquyen)
                    .addComponent(btn_thuhoiquyen))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhóm quyền"));

        btn_capquyen2.setText("Cấp");
        btn_capquyen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capquyen2ActionPerformed(evt);
            }
        });

        btn_thuhoiquyen2.setText("Thu Hồi");
        btn_thuhoiquyen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thuhoiquyen2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Tên nhóm quyền:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_capquyen2)
                    .addComponent(jLabel9))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_tennhomquyen)
                        .addContainerGap())
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_thuhoiquyen2)
                        .addGap(54, 54, 54))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_tennhomquyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_capquyen2)
                    .addComponent(btn_thuhoiquyen2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tenuser))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_tenuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tạo mới, thêm, xóa nhóm quyền"));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Gán quyền cho role"));

        rd_createsession1.setText("CREATE SESSION");

        rd_createtable1.setText("CREATE TABLE");

        rd_createprocedure1.setText("CREATE PROCEDURE");

        rd_createuser.setText("CREATE USER");

        btn_thuhoiquyen1.setText("Gán");
        btn_thuhoiquyen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thuhoiquyen1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd_createsession1)
                    .addComponent(rd_createtable1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd_createuser)
                    .addComponent(rd_createprocedure1))
                .addGap(28, 28, 28))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btn_thuhoiquyen1)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_createsession1)
                    .addComponent(rd_createprocedure1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_createuser)
                    .addComponent(rd_createtable1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_thuhoiquyen1)
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Tạo / Xóa role"));

        jLabel10.setText("Tên nhóm quyền:");

        btn_taorole.setText("Tạo");
        btn_taorole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taoroleActionPerformed(evt);
            }
        });

        btn_xoarole.setText("Xóa");
        btn_xoarole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaroleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(btn_taorole))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tennhomquyen1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btn_xoarole)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(txt_tennhomquyen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_xoarole)
                            .addComponent(btn_taorole))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Profile"));

        jLabel11.setText("Tên profile:");

        btn_suaprofile.setText("Sửa");
        btn_suaprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaprofileActionPerformed(evt);
            }
        });

        btn_xoaprofile.setText("Xóa");
        btn_xoaprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaprofileActionPerformed(evt);
            }
        });

        jLabel8.setText("Tham số:");

        jLabel12.setText("Giá trị:");

        btn_taoprofile.setText("Tạo");
        btn_taoprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taoprofileActionPerformed(evt);
            }
        });

        FAILED_LOGIN_ATTEMPTS.setText("FAILED_LOGIN_ATTEMPTS");
        FAILED_LOGIN_ATTEMPTS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FAILED_LOGIN_ATTEMPTSMouseClicked(evt);
            }
        });
        FAILED_LOGIN_ATTEMPTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAILED_LOGIN_ATTEMPTSActionPerformed(evt);
            }
        });

        PASSWORD_LIFE_TIME.setText("PASSWORD_LIFE_TIME");
        PASSWORD_LIFE_TIME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PASSWORD_LIFE_TIMEMouseClicked(evt);
            }
        });
        PASSWORD_LIFE_TIME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORD_LIFE_TIMEActionPerformed(evt);
            }
        });

        PASSWORD_REUSE_TIME.setText("PASSWORD_REUSE_TIME");
        PASSWORD_REUSE_TIME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PASSWORD_REUSE_TIMEMouseClicked(evt);
            }
        });
        PASSWORD_REUSE_TIME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORD_REUSE_TIMEActionPerformed(evt);
            }
        });

        PASSWORD_REUSE_MAX.setText("PASSWORD_REUSE_MAX");
        PASSWORD_REUSE_MAX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PASSWORD_REUSE_MAXMouseClicked(evt);
            }
        });

        PASSWORD_GRACE_TIME.setText("PASSWORD_GRACE_TIME");
        PASSWORD_GRACE_TIME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PASSWORD_GRACE_TIMEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_suaprofile)
                        .addGap(83, 83, 83)
                        .addComponent(btn_xoaprofile)
                        .addGap(108, 108, 108))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PASSWORD_LIFE_TIME)
                                    .addComponent(PASSWORD_REUSE_TIME)
                                    .addComponent(PASSWORD_REUSE_MAX)
                                    .addComponent(PASSWORD_GRACE_TIME))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_giatri_PASSWORD_GRACE_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(txt_giatri_PASSWORD_REUSE_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(btn_taoprofile))
                                    .addComponent(txt_giatri_PASSWORD_LIFE_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_giatri_PASSWORD_REUSE_MAX, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(FAILED_LOGIN_ATTEMPTS)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txt_giatri_FAILED_LOGIN_ATTEMPTS, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_thamso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_tenprofile))))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenprofile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_thamso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_xoaprofile)
                            .addComponent(btn_suaprofile))
                        .addGap(115, 115, 115)
                        .addComponent(btn_taoprofile))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FAILED_LOGIN_ATTEMPTS)
                            .addComponent(txt_giatri_FAILED_LOGIN_ATTEMPTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PASSWORD_LIFE_TIME)
                            .addComponent(txt_giatri_PASSWORD_LIFE_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PASSWORD_REUSE_TIME)
                            .addComponent(txt_giatri_PASSWORD_REUSE_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PASSWORD_REUSE_MAX)
                            .addComponent(txt_giatri_PASSWORD_REUSE_MAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PASSWORD_GRACE_TIME)
                            .addComponent(txt_giatri_PASSWORD_GRACE_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cấp quyền đối tượng"));

        jButton2.setText("Cấp");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(62, 62, 62))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Audit"));

        jButton3.setText("quản lí dữ liệu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(39, 39, 39))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        thoat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/THOAT.png"))); // NOI18N
        thoat4.setText("Thoát");
        thoat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoat4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thoat4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(thoat4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_matkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matkhauActionPerformed
    public String quota() {
        if (rd_mb.isSelected()) {
            return "M";
        } else if (rd_kb.isSelected()) {
            return "K";
        } else {
            return "G";
        }
    }

    public String tablespace() {
        if (rd_tbs1.isSelected()) {
            return rd_tbs1.getText();
        } else if (rd_tbs2.isSelected()) {
            return rd_tbs2.getText();
        } else if (rd_tbs3.isSelected()) {
            return rd_tbs3.getText();
        } else {
            return rd_tbs1.getText();
        }
    }
    private void btn_taoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoActionPerformed
        // TODO add your handling code here:
        rd_tbs1.setEnabled(false);
        rd_tbs2.setEnabled(false);
        rd_tbs3.setEnabled(false);
        rd_tbs4.setEnabled(false);
        btn_sua.setEnabled(true);
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "CREATE USER " + txt_ten.getText() + " IDENTIFIED BY " + txt_matkhau.getText()
                    + " DEFAULT TABLESPACE " + tablespace()
                    + " QUOTA " + txt_quota.getText() + quota() + " ON " + tablespace() + " PROFILE " + rd_ktramk.getText();
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btn_taoActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "ALTER USER " + txt_ten.getText() + " IDENTIFIED BY " + txt_matkhau.getText()
                    + " DEFAULT TABLESPACE " + tablespace()
                    + " QUOTA " + txt_quota.getText() + quota() + " ON " + tablespace();
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        rd_tbs1.setEnabled(true);
        rd_tbs2.setEnabled(true);
        rd_tbs3.setEnabled(true);
        rd_tbs4.setEnabled(true);
        btn_sua.setEnabled(false);
        txt_ten.setText("");
        txt_matkhau.setText("");
        txt_quota.setText("");
        rd_mb.setSelected(true);
        rd_tbs1.setSelected(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "DROP USER " + txt_ten.getText() + " CASCADE";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_themTablespaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themTablespaceActionPerformed
        // TODO add your handling code here:
        Them_Xoa_Tablespace nvf = new Them_Xoa_Tablespace();
        nvf.setVisible(true);
    }//GEN-LAST:event_btn_themTablespaceActionPerformed

    private void btn_xoaTablespaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaTablespaceActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql1 = "DROP TABLESPACE " + txt_Tablespace.getText() + " INCLUDING CONTENTS CASCADE CONSTRAINTS";
            String sql2 = "DROP TABLESPACE " + txt_Tablespace.getText() + " INCLUDING CONTENTS AND DATAFILES";
            // Thưc thi câu lệnh truy vấn
            if (jRadioButton_mat.isSelected()) {
                System.out.println(sql2);
                ResultSet rs = st.executeQuery(sql2);

            } else {
                System.out.println(sql1);
                ResultSet rs = st.executeQuery(sql1);

            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btn_xoaTablespaceActionPerformed

    private void txt_datafileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_datafileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_datafileActionPerformed

    private void btn_themDatafileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themDatafileActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "alter tablespace " + txt_ten.getText() + " drop datafile '" + txt_datafile.getText() + "'";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
        }
    }//GEN-LAST:event_btn_themDatafileActionPerformed

    private void btn_xoaDatafileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaDatafileActionPerformed
        // TODO add your handling code here: app_ff.dbf
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "alter tablespace " + txt_ten.getText() + " drop datafile '" + txt_datafile.getText() + "'";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }
        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại Công!");
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btn_xoaDatafileActionPerformed

    public String quyenchouser() {
        if (rd_createsession.isSelected()) {
            return rd_createsession.getText();
        } else if (rd_createprocedure.isSelected()) {
            return rd_createprocedure.getText();
        } else if (rd_createtable.isSelected()) {
            return rd_createtable.getText();
        } else {
            return rd_createtrigger.getText();
        }
    }
    private void btn_capquyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capquyenActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        if(txt_tenuser.getText().equals(""))
        {JOptionPane.showMessageDialog(rootPane, "Nhập Tên User !");}
        else{
        try {
            st = (Statement) con.createStatement();
            String sql = "GRANT " + quyenchouser() + " TO " + txt_tenuser.getText();
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            ex.printStackTrace();

        }
        }
    }//GEN-LAST:event_btn_capquyenActionPerformed

    private void btn_thuhoiquyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thuhoiquyenActionPerformed
        // TODO add your handling code here:
        if(txt_tenuser.getText().equals(""))
        {JOptionPane.showMessageDialog(rootPane, "Nhập Tên User !");}
        else{
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "REVOKE " + quyenchouser() + " FROM " + txt_tenuser.getText();
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            ex.printStackTrace();

        }
        }
    }//GEN-LAST:event_btn_thuhoiquyenActionPerformed

    private void btn_xoaroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaroleActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        if(txt_tennhomquyen1.getText().equals(""))
        {JOptionPane.showMessageDialog(rootPane, "Nhập Tên nhóm quyền !");}
        else{
        try {
            st = (Statement) con.createStatement();
            String sql = "DROP ROLE " + txt_tennhomquyen1.getText();
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            ex.printStackTrace();

        }
        }
    }//GEN-LAST:event_btn_xoaroleActionPerformed

    public String quyenchorole() {
        if (rd_createsession1.isSelected()) {
            return rd_createsession1.getText();
        } else if (rd_createprocedure1.isSelected()) {
            return rd_createprocedure1.getText();
        } else if (rd_createtable1.isSelected()) {
            return rd_createtable1.getText();
        } else {
            return rd_createuser.getText();
        }
    }
    private void btn_thuhoiquyen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thuhoiquyen1ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        if(txt_tennhomquyen1.getText().equals(""))
        {JOptionPane.showMessageDialog(rootPane, "Nhập Tên nhóm quyền !");}
        else{
        try {
            st = (Statement) con.createStatement();
            String sql = "GRANT " + quyenchorole() + " TO " + txt_tennhomquyen1.getText();
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            ex.printStackTrace();

        }
        }
    }//GEN-LAST:event_btn_thuhoiquyen1ActionPerformed

    private void btn_capquyen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capquyen2ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        if(txt_tennhomquyen.getText().equals("")||txt_tenuser.getText().equals(""))
        {JOptionPane.showMessageDialog(rootPane, "Nhập đầy đủ Tên nhóm quyền và Tên User!");}
        else{
        try {
            st = (Statement) con.createStatement();
            String sql = "GRANT " + txt_tennhomquyen.getText() + " TO " + txt_tenuser.getText();
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            ex.printStackTrace();

        }
        }
    }//GEN-LAST:event_btn_capquyen2ActionPerformed

    private void btn_thuhoiquyen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thuhoiquyen2ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        if(txt_tennhomquyen.getText().equals("")||txt_tenuser.getText().equals(""))
        {JOptionPane.showMessageDialog(rootPane, "Nhập đầy đủ Tên nhóm quyền và Tên User!");}
        else{
        try {
            st = (Statement) con.createStatement();
            String sql = "REVOKE " + txt_tennhomquyen.getText() + " FROM " + txt_tenuser.getText();
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            
            ex.printStackTrace();

        }
        }
    }//GEN-LAST:event_btn_thuhoiquyen2ActionPerformed

    private void btn_taoroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoroleActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        if(txt_tennhomquyen1.getText().equals(""))
        {JOptionPane.showMessageDialog(rootPane, "Nhập Tên nhóm quyền !");}
        else{
        try {
            st = (Statement) con.createStatement();
            String sql = "CREATE ROLE " + txt_tennhomquyen1.getText();
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            ex.printStackTrace();

        }
        }
    }//GEN-LAST:event_btn_taoroleActionPerformed

    private void btn_suaprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaprofileActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "ALTER PROFILE " + txt_tenprofile.getText() + " LIMIT " + txt_thamso.getText() ;
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btn_suaprofileActionPerformed

    private void btn_xoaprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaprofileActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "DROP PROFILE " + txt_tenprofile.getText() + " CASCADE";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại!");
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btn_xoaprofileActionPerformed
    public Boolean ktratxt() {
        if(txt_tenprofile.getText().equals("")||txt_thamso.getText().equals(""))
        {
             JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập và chọn đầy đủ thông tin!!");
             return false;
        }return true;
    }
    private void btn_taoprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoprofileActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "CREATE PROFILE " + txt_tenprofile.getText() + " LIMIT " + txt_thamso.getText();
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
                JOptionPane.showMessageDialog(rootPane, "Thành Công!");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            JOptionPane.showMessageDialog(rootPane, "Thất Bại !");
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btn_taoprofileActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CapQuyenDoiTuong nvf = new CapQuyenDoiTuong();
        nvf.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        audit nvf = new audit();
        nvf.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void FAILED_LOGIN_ATTEMPTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAILED_LOGIN_ATTEMPTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FAILED_LOGIN_ATTEMPTSActionPerformed

    private void PASSWORD_LIFE_TIMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORD_LIFE_TIMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORD_LIFE_TIMEActionPerformed

    private void PASSWORD_REUSE_TIMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORD_REUSE_TIMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORD_REUSE_TIMEActionPerformed

    public void load_thamsorong(String d) {

        txt_thamso.setText(String.valueOf(d));

    }

    public void load_thamsotontai(String c, String d) {

        txt_thamso.setText(String.valueOf(c) + " " + String.valueOf(d));

    }
    private void FAILED_LOGIN_ATTEMPTSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FAILED_LOGIN_ATTEMPTSMouseClicked
        // TODO add your handling code here:
        if (txt_giatri_FAILED_LOGIN_ATTEMPTS.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền Giá Trị!");
            FAILED_LOGIN_ATTEMPTS.setSelected(false);
        } else {
            if (FAILED_LOGIN_ATTEMPTS.isSelected()) {
                String c = txt_thamso.getText();
                String a = String.valueOf(FAILED_LOGIN_ATTEMPTS.getText());
                String b = String.valueOf(txt_giatri_FAILED_LOGIN_ATTEMPTS.getText());
                String d = a + " " + b;
                if (txt_thamso.getText().equals("")) {
                    load_thamsorong(d);
                } else {
                    load_thamsotontai(c, d);
                }
            } else {
                txt_thamso.setText("");
                FAILED_LOGIN_ATTEMPTS.setSelected(false);
            }
        }
    }//GEN-LAST:event_FAILED_LOGIN_ATTEMPTSMouseClicked

    private void PASSWORD_LIFE_TIMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PASSWORD_LIFE_TIMEMouseClicked
        // TODO add your handling code here:
        if (txt_giatri_PASSWORD_LIFE_TIME.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền Giá Trị!");
            PASSWORD_LIFE_TIME.setSelected(false);
        } else {
            if (PASSWORD_LIFE_TIME.isSelected()) {
                String c = txt_thamso.getText();
                String a = String.valueOf(PASSWORD_LIFE_TIME.getText());
                String b = String.valueOf(txt_giatri_PASSWORD_LIFE_TIME.getText());
                String d = a + " " + b;
                if (txt_thamso.getText().equals("")) {
                    load_thamsorong(d);
                } else {
                    load_thamsotontai(c, d);
                }
            } else {
                txt_thamso.setText("");
                PASSWORD_LIFE_TIME.setSelected(false);
            }
        }
    }//GEN-LAST:event_PASSWORD_LIFE_TIMEMouseClicked

    private void PASSWORD_REUSE_TIMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PASSWORD_REUSE_TIMEMouseClicked
        // TODO add your handling code here:
        if (txt_giatri_PASSWORD_REUSE_TIME.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền Giá Trị!");
            PASSWORD_REUSE_TIME.setSelected(false);
        } else {
            if (PASSWORD_REUSE_TIME.isSelected()) {
                String c = txt_thamso.getText();
                String a = String.valueOf(PASSWORD_REUSE_TIME.getText());
                String b = String.valueOf(txt_giatri_PASSWORD_REUSE_TIME.getText());
                String d = a + " " + b;
                if (txt_thamso.getText().equals("")) {
                    load_thamsorong(d);
                } else {
                    load_thamsotontai(c, d);
                }
            } else {
                txt_thamso.setText("");
                PASSWORD_REUSE_TIME.setSelected(false);
            }
        }
    }//GEN-LAST:event_PASSWORD_REUSE_TIMEMouseClicked

    private void PASSWORD_REUSE_MAXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PASSWORD_REUSE_MAXMouseClicked
        // TODO add your handling code here:
        if (txt_giatri_PASSWORD_REUSE_MAX.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền Giá Trị!");
            PASSWORD_REUSE_MAX.setSelected(false);
        } else {
            if (PASSWORD_REUSE_MAX.isSelected()) {
                String c = txt_thamso.getText();
                String a = String.valueOf(PASSWORD_REUSE_MAX.getText());
                String b = String.valueOf(txt_giatri_PASSWORD_REUSE_MAX.getText());
                String d = a + " " + b;
                if (txt_thamso.getText().equals("")) {
                    load_thamsorong(d);
                } else {
                    load_thamsotontai(c, d);
                }
            } else {
                txt_thamso.setText("");
                PASSWORD_REUSE_MAX.setSelected(false);
            }
        }
    }//GEN-LAST:event_PASSWORD_REUSE_MAXMouseClicked

    private void PASSWORD_GRACE_TIMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PASSWORD_GRACE_TIMEMouseClicked
        // TODO add your handling code here:
        if (txt_giatri_PASSWORD_GRACE_TIME.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền Giá Trị!");
            PASSWORD_GRACE_TIME.setSelected(false);
        } else {
            if (PASSWORD_GRACE_TIME.isSelected()) {
                String c = txt_thamso.getText();
                String a = String.valueOf(PASSWORD_GRACE_TIME.getText());
                String b = String.valueOf(txt_giatri_PASSWORD_GRACE_TIME.getText());
                String d = a + " " + b;
                if (txt_thamso.getText().equals("")) {
                    load_thamsorong(d);
                } else {
                    load_thamsotontai(c, d);
                }
            } else {
                txt_thamso.setText("");
                PASSWORD_GRACE_TIME.setSelected(false);
            }
        }
    }//GEN-LAST:event_PASSWORD_GRACE_TIMEMouseClicked

    private void thoat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoat4ActionPerformed
        // TODO add your handling code here:
        thoat4.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát chương"
            + " trình không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_thoat4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeThong2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeThong2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeThong2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeThong2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeThong2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox FAILED_LOGIN_ATTEMPTS;
    private javax.swing.JCheckBox PASSWORD_GRACE_TIME;
    private javax.swing.JCheckBox PASSWORD_LIFE_TIME;
    private javax.swing.JCheckBox PASSWORD_REUSE_MAX;
    private javax.swing.JCheckBox PASSWORD_REUSE_TIME;
    private javax.swing.JButton btn_capquyen;
    private javax.swing.JButton btn_capquyen2;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_suaprofile;
    private javax.swing.JButton btn_tao;
    private javax.swing.JButton btn_taoprofile;
    private javax.swing.JButton btn_taorole;
    private javax.swing.JButton btn_themDatafile;
    private javax.swing.JButton btn_themTablespace;
    private javax.swing.JButton btn_thuhoiquyen;
    private javax.swing.JButton btn_thuhoiquyen1;
    private javax.swing.JButton btn_thuhoiquyen2;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton btn_xoaDatafile;
    private javax.swing.JButton btn_xoaTablespace;
    private javax.swing.JButton btn_xoaprofile;
    private javax.swing.JButton btn_xoarole;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton_con;
    private javax.swing.JRadioButton jRadioButton_mat;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rd_createprocedure;
    private javax.swing.JRadioButton rd_createprocedure1;
    private javax.swing.JRadioButton rd_createsession;
    private javax.swing.JRadioButton rd_createsession1;
    private javax.swing.JRadioButton rd_createtable;
    private javax.swing.JRadioButton rd_createtable1;
    private javax.swing.JRadioButton rd_createtrigger;
    private javax.swing.JRadioButton rd_createuser;
    private javax.swing.JRadioButton rd_gb;
    private javax.swing.JRadioButton rd_kb;
    private javax.swing.JRadioButton rd_ktramk;
    private javax.swing.JRadioButton rd_mb;
    private javax.swing.JRadioButton rd_tbs1;
    private javax.swing.JRadioButton rd_tbs2;
    private javax.swing.JRadioButton rd_tbs3;
    private javax.swing.JRadioButton rd_tbs4;
    private javax.swing.JButton thoat4;
    private javax.swing.JTextField txt_Tablespace;
    private javax.swing.JTextField txt_datafile;
    private javax.swing.JTextField txt_giatri_FAILED_LOGIN_ATTEMPTS;
    private javax.swing.JTextField txt_giatri_PASSWORD_GRACE_TIME;
    private javax.swing.JTextField txt_giatri_PASSWORD_LIFE_TIME;
    private javax.swing.JTextField txt_giatri_PASSWORD_REUSE_MAX;
    private javax.swing.JTextField txt_giatri_PASSWORD_REUSE_TIME;
    private javax.swing.JTextField txt_matkhau;
    private javax.swing.JTextField txt_quota;
    private javax.swing.JTextField txt_size;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_ten1;
    private javax.swing.JTextField txt_tennhomquyen;
    private javax.swing.JTextField txt_tennhomquyen1;
    private javax.swing.JTextField txt_tenprofile;
    private javax.swing.JTextField txt_tenuser;
    private javax.swing.JTextField txt_thamso;
    // End of variables declaration//GEN-END:variables
}
