/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.Form;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import qlks.CThoadon;
import qlks.HoaDon;
import qlks.KhachHang;
import static qlks.MyConnection.getConnection;
import static qlks.Form.DangNhap_Form.Hostname;
import static qlks.Form.DangNhap_Form.Name_Ac;
import static qlks.Form.DangNhap_Form.Password;
import static qlks.Form.DangNhap_Form.Port;
import static qlks.Form.DangNhap_Form.SID;
import static qlks.Form.DangNhap_Form.Username;
import static qlks.Form.DangNhap_Form.check;
import qlks.thuephong;

/**
 *
 * @author khoa
 */
public class KhachHang_Form extends javax.swing.JFrame {

    private String imageLocation;

    public KhachHang_Form() {
        initComponents();
        getConnection(Hostname,Port,SID,Username,Password);
        hienThiDanhSachKhachHang();
        enable();
    }
    Vector title = new Vector();
    Vector data = new Vector();
    Connection con = null;
    Statement st = null;

    public  void enable()
    {
        if (check == true && Name_Ac.equals("sys"))
        {
            jButton4.setEnabled(false);
        }
        if (check == true && Name_Ac.equals("hr"))
        {
            jButton4.setEnabled(true);
        }
    }
    public ArrayList<KhachHang> layDanhSachKhachHang(String sql) {
        ArrayList<KhachHang> dskh = new ArrayList<KhachHang>();
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();

            // Thưcj thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            KhachHang kh;
            while (rs.next()) {
                kh = new KhachHang(rs.getString("MAKH"), rs.getString("TENKH"), 
                        rs.getDate("NGAYSINH"), rs.getString("GIOITINH"), rs.getString("CMND"), 
                        rs.getString("QUOCTICH"), rs.getString("SDT"), rs.getString("LOAIKH"));

                //Thêm vào danh sách
                dskh.add(kh);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        return dskh;
    }

    public void hienThiDanhSachKhachHang() {
        String sql = "SELECT * FROM hr.khachhang";
        String colTieuDe1[] = new String[]{"Mã Khách Hàng", "Tên Khách Hàng", "Ngày Sinh", "Giới Tính", 
                                    "Chứng Minh Nhân Dân", "Quốc Tịch", "Số Điện Thoại", "Loại Khách"};
        ArrayList<KhachHang> dskh = layDanhSachKhachHang(sql);

        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dskh.size(); i++) {

            row = new Object[8];

            // GÁN GIÁ TRỊ
            row[0] = dskh.get(i).getMAKH();
            row[1] = dskh.get(i).getTENKH();
            row[2] = dskh.get(i).getNGAYSINH();
            row[3] = dskh.get(i).getGIOITINH();
            row[4] = dskh.get(i).getCMND();
            row[5] = dskh.get(i).getQUOCTICH();
            row[6] = dskh.get(i).getSDT();
            row[7] = dskh.get(i).getLOAIKH();

            model.addRow(row);
        }

        //    }catch(ArrayIndexOutOfBoundsException ex){
        jTableKhachhang.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldMAKH = new javax.swing.JTextField();
        jTextFieldTENKH = new javax.swing.JTextField();
        jTextFieldCMND = new javax.swing.JTextField();
        jTextFieldQUOCTICH = new javax.swing.JTextField();
        jTextFieldGIOITINHKH = new javax.swing.JTextField();
        jTextFieldSDT = new javax.swing.JTextField();
        them1 = new javax.swing.JButton();
        sua1 = new javax.swing.JButton();
        xoa1 = new javax.swing.JButton();
        thoat1 = new javax.swing.JButton();
        jButtonclear2 = new javax.swing.JButton();
        jTextFieldNGAYSINH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLOAIKH = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableKhachhang = new javax.swing.JTable();
        btn_sapxep = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_tenkhach = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Khách Hàng"));

        jLabel10.setText("Mã Khách Hàng");

        jLabel11.setText("Tên Khách Hàng");

        jLabel12.setText("Chứng Minh Nhân Dân");

        jLabel13.setText("Quốc Tịch");

        jLabel14.setText("Giới Tính");

        jLabel16.setText("Số Điện Thoại");

        jTextFieldMAKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMAKHActionPerformed(evt);
            }
        });
        jTextFieldMAKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMAKHKeyPressed(evt);
            }
        });

        jTextFieldTENKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTENKHActionPerformed(evt);
            }
        });

        jTextFieldCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCMNDKeyTyped(evt);
            }
        });

        jTextFieldGIOITINHKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldGIOITINHKHKeyPressed(evt);
            }
        });

        them1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/THEM.png"))); // NOI18N
        them1.setText("Thêm");
        them1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them1ActionPerformed(evt);
            }
        });

        sua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/SUA.png"))); // NOI18N
        sua1.setText("Sửa");
        sua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua1ActionPerformed(evt);
            }
        });

        xoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/XOA.png"))); // NOI18N
        xoa1.setText("Xóa");
        xoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa1ActionPerformed(evt);
            }
        });

        thoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/THOAT.png"))); // NOI18N
        thoat1.setText("Thoát");
        thoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoat1ActionPerformed(evt);
            }
        });

        jButtonclear2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/CLEAR.png"))); // NOI18N
        jButtonclear2.setText("Clear");
        jButtonclear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclear2ActionPerformed(evt);
            }
        });

        jTextFieldNGAYSINH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNGAYSINHKeyTyped(evt);
            }
        });

        jLabel1.setText("Ngày Sinh");

        jLabel3.setText("Loại Khách");

        jTextFieldLOAIKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLOAIKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(them1)
                            .addComponent(xoa1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(sua1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonclear2))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(thoat1)
                                .addGap(108, 108, 108))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCMND)
                            .addComponent(jTextFieldGIOITINHKH)
                            .addComponent(jTextFieldNGAYSINH)
                            .addComponent(jTextFieldLOAIKH)
                            .addComponent(jTextFieldQUOCTICH)
                            .addComponent(jTextFieldTENKH)
                            .addComponent(jTextFieldMAKH, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldSDT))))
                .addGap(27, 27, 27))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldMAKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTENKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLOAIKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNGAYSINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldGIOITINHKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldQUOCTICH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them1)
                    .addComponent(sua1)
                    .addComponent(jButtonclear2))
                .addGap(32, 32, 32)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xoa1)
                    .addComponent(thoat1))
                .addGap(22, 22, 22))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/khachhang.png"))); // NOI18N
        jLabel9.setText("QUẢN LÝ KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jTableKhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKhachhangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableKhachhang);

        btn_sapxep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/sapxep.png"))); // NOI18N
        btn_sapxep.setText("Sắp Xếp");
        btn_sapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sapxepActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/xemphong.png"))); // NOI18N
        jButton1.setText("Lấy 3 Nam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tìm kiếm"));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/timkiem.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập Tên khách hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_tenkhach, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_tenkhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/xemphong.png"))); // NOI18N
        jButton3.setText("Xem TT Thuê Phòng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/xemphong.png"))); // NOI18N
        jButton4.setText("Số Lượng KH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(btn_sapxep))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(9, 9, 9)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sapxep))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3)
                                .addComponent(jButton1))
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKhachhangMouseClicked
        // TODO add your handling code here:
        int i = jTableKhachhang.getSelectedRow();
        TableModel model = jTableKhachhang.getModel();
        jTextFieldMAKH.setText(model.getValueAt(i, 0).toString());
        jTextFieldTENKH.setText(model.getValueAt(i, 1).toString());
        jTextFieldNGAYSINH.setText(model.getValueAt(i, 2).toString());
        jTextFieldGIOITINHKH.setText(model.getValueAt(i, 3).toString());
        jTextFieldCMND.setText(model.getValueAt(i, 4).toString());
        jTextFieldQUOCTICH.setText(model.getValueAt(i, 5).toString());
        jTextFieldSDT.setText(model.getValueAt(i, 6).toString());
        jTextFieldLOAIKH.setText(model.getValueAt(i, 7).toString());
    }//GEN-LAST:event_jTableKhachhangMouseClicked

    private void jButtonclear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclear2ActionPerformed
        // TODO add your handling code here:
        jTextFieldMAKH.setText("");
        jTextFieldTENKH.setText("");
        jTextFieldLOAIKH.setText("");
        jTextFieldNGAYSINH.setText("");
        jTextFieldCMND.setText("");
        jTextFieldQUOCTICH.setText("");
        jTextFieldGIOITINHKH.setText("");
        jTextFieldSDT.setText("");
        jTextFieldMAKH.requestFocus();
        hienThiDanhSachKhachHang();
    }//GEN-LAST:event_jButtonclear2ActionPerformed

    private void thoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoat1ActionPerformed
        // TODO add your handling code here:
        thoat1.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát chương"
                + " trình không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_thoat1ActionPerformed

    public ArrayList<thuephong> layDanhSachTP(String sql) {
        ArrayList<thuephong> d = new ArrayList<thuephong>();
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();

            // Thưcj thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            thuephong w;
            while (rs.next()) {
                w = new thuephong(rs.getString("MADK"), rs.getString("MAKH"), rs.getString("SOPHONG"), rs.getDate("NGAYDK"), rs.getDate("NGAYDI"), rs.getInt("SONGAY"));

                //Thêm vào danh sách
                d.add(w);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        return d;
    }
    
    ArrayList<thuephong> dst = layDanhSachTP("select * from hr.thuephong");
    public static Boolean kiemtrat(ArrayList<thuephong> dst,String makh) {
        for (thuephong c : dst) {
            if (c.getMAKH().equals(makh)) {
                return true;
            }
        }
        return false;
    }
    public Boolean kiemtrathue() {
        if (kiemtrat(dst, jTextFieldMAKH.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Khách Hàng này đang Thuê Phòng, không xóa được!!", "Thong bao", 2);
            return true;
        }
        return false;
    }
    public ArrayList<HoaDon> layDanhSachHoaDon(String sql) {
        ArrayList<HoaDon> dshd = new ArrayList<HoaDon>();
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();

            // Thưcj thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            HoaDon hd;
            while (rs.next()) {
                hd = new HoaDon(rs.getString("MAHD"), rs.getString("TENHD"), rs.getString("MADV"), rs.getString("MAKH"), rs.getDate("NGAYLAP"), rs.getString("MANV"),rs.getString("SOPHONG"));

                //Thêm vào danh sách
                dshd.add(hd);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        return dshd;
    }
    ArrayList<HoaDon> dshd = layDanhSachHoaDon("select * from hr.HoaDon");
    public static Boolean kiemtrathd(ArrayList<HoaDon> dshd,String makh) {
        for (HoaDon c : dshd) {
            if (c.getMAKH().equals(makh)) {
                return true;
            }
        }
        return false;
    }
    public Boolean kiemtrathuehd() {
        if (kiemtrathd(dshd, jTextFieldMAKH.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Khách Hàng này đang Thuê Phòng, không xóa được!!", "Thong bao", 2);
            return true;
        }
        return false;
    }
    private void xoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoa1ActionPerformed
        // TODO add your handling code here:
        int pos = jTableKhachhang.getSelectedRow();
        if (pos < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn Hãy Chọn 1 dòng");
        }
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        if(kiemtrathue()==false&&kiemtrathuehd()==false)
        {
        try {
            // Tạo một đối tượng để thực hiện công việc
            st = (Statement) con.createStatement();
            String query = "DELETE FROM hr.khachhang WHERE MAKH = '" + jTextFieldMAKH.getText() + "'";
            st.executeUpdate(query);
            hienThiDanhSachKhachHang();

        } catch (Exception ex) {

            ex.printStackTrace();
        }
        }
    }//GEN-LAST:event_xoa1ActionPerformed

    private void sua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua1ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        int pos = jTableKhachhang.getSelectedRow();
        if (pos < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn Hãy Chọn 1 dòng");
        } else {
            try {
                if (kiemtratxt()&&ktraLOAIKH()&&ktragioitinh()) {
                    // Tạo một đối tượng để thực hiện công việc
                    int i = -1;
                    st = (Statement) con.createStatement();
                    String query = "update hr.khachhang set tenkh='" + jTextFieldTENKH.getText() + "',ngaysinh=TO_DATE('"
                            + jTextFieldNGAYSINH.getText() + "','YYYY/MM/DD'),Gioitinh='" + jTextFieldGIOITINHKH.getText() + "',cmnd='"
                            + jTextFieldCMND.getText() + "',quoctich='" + jTextFieldQUOCTICH.getText()
                            + "',sdt='" + jTextFieldSDT.getText() + "',loaikh='" + jTextFieldLOAIKH.getText() 
                            + "' where makh='" + jTextFieldMAKH.getText() + "'";
                    System.out.print(query);
                    i = st.executeUpdate(query);
                    if (i != -1) {
                        hienThiDanhSachKhachHang();
                    }
                }
            } catch (Exception ex) {

                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_sua1ActionPerformed
    public Boolean kiemtrangaysinh() {
        try {
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            Date date = df.parse(jTextFieldNGAYSINH.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập kiểu dữ liệu ngày sinh là dd/mm/yyyy", "Thong bao", 2);
            return false;
        }
        return true;
    }

    public Boolean kiemtratxt() {
        if (jTextFieldMAKH.getText().equals("") || jTextFieldTENKH.getText().equals("") || jTextFieldLOAIKH.getText().equals("") || jTextFieldGIOITINHKH.getText().equals("") || jTextFieldCMND.getText().equals("")
                || jTextFieldQUOCTICH.getText().equals("") || jTextFieldSDT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui long nhap day du thong tin", "Thong bao", 2);
            return false;
        }
        return true;
    }
    public boolean  ktraLOAIKH()
    {
        if(jTextFieldLOAIKH.getText().toString().equals("VIP")
                ||jTextFieldLOAIKH.getText().toString().equals("THAN THIET")
                ||jTextFieldLOAIKH.getText().toString().equals("BINH THUONG"))
        {
            return  true;
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập loại khách là VIP or THAN THIET or BINH THUONG!!", "Thong bao", 2);
           return  false;
        }
    }
    public boolean  ktragioitinh()
    {
        if(jTextFieldGIOITINHKH.getText().toString().equals("NAM")
                ||jTextFieldGIOITINHKH.getText().toString().equals("NU"))
        {
            return  true;
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập lại giới tính là NAM or NU!!", "Thong bao", 2);
           return  false;
        }
    }
    private void them1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them1ActionPerformed
        // TODO add your handling code here:
        if (kiemtrangaysinh() && kiemtratxt()&&ktraLOAIKH()&&ktragioitinh()) {
            Connection con = getConnection(Hostname,Port,SID,Username,Password);
            try {
                // Tạo một đối tượng để thực hiện công việc
                st = (Statement) con.createStatement();
                String query = "INSERT INTO hr.khachhang VALUES('" + jTextFieldMAKH.getText() + "',"
                        + "'" + jTextFieldTENKH.getText() + "',TO_DATE('" + jTextFieldNGAYSINH.getText() + "','DD/MM/YYYY'), '"
                        + jTextFieldGIOITINHKH.getText() + "', '" + jTextFieldCMND.getText() + "', '"
                        + jTextFieldQUOCTICH.getText() + "','" + jTextFieldSDT.getText() + "','" + jTextFieldLOAIKH.getText() + "')";
                System.out.print(query);
                st.execute(query);
                hienThiDanhSachKhachHang();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_them1ActionPerformed

    private void jTextFieldTENKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTENKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTENKHActionPerformed

    private void jTextFieldMAKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMAKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMAKHActionPerformed

    private void btn_sapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sapxepActionPerformed
        // TODO add your handling code here:
        String sql = "select * from hr.khachhang order by 8";
        String colTieuDe1[] = new String[]{"Mã Khách Hàng", "Tên Khách Hàng", "Ngày Sinh", "Giới Tính", 
            "Chứng Minh Nhân Dân", "Quốc Tịch", "Số Điện Thoại","Loại Khách"};
        ArrayList<KhachHang> dskh = layDanhSachKhachHang(sql);

        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dskh.size(); i++) {

            row = new Object[8];

            // GÁN GIÁ TRỊ
            row[0] = dskh.get(i).getMAKH();
            row[1] = dskh.get(i).getTENKH();
            row[2] = dskh.get(i).getNGAYSINH();
            row[3] = dskh.get(i).getGIOITINH();
            row[4] = dskh.get(i).getCMND();
            row[5] = dskh.get(i).getQUOCTICH();
            row[6] = dskh.get(i).getSDT();
            row[7] = dskh.get(i).getLOAIKH();

            model.addRow(row);
        }
        jTableKhachhang.setModel(model);
    }//GEN-LAST:event_btn_sapxepActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from hr.khachhang where gioitinh='NAM' order by 1 fetch first 3  row only";
        String colTieuDe1[] = new String[]{"Mã Khách Hàng", "Tên Khách Hàng", "Ngày Sinh", "Giới Tính", 
                              "Chứng Minh Nhân Dân", "Quốc Tịch", "Số Điện Thoại", "loại khách"};
        ArrayList<KhachHang> dskh = layDanhSachKhachHang(sql);

        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dskh.size(); i++) {

            row = new Object[8];

            // GÁN GIÁ TRỊ
            row[0] = dskh.get(i).getMAKH();
            row[1] = dskh.get(i).getTENKH();
            row[2] = dskh.get(i).getNGAYSINH();
            row[3] = dskh.get(i).getGIOITINH();
            row[4] = dskh.get(i).getCMND();
            row[5] = dskh.get(i).getQUOCTICH();
            row[6] = dskh.get(i).getSDT();
            row[7] = dskh.get(i).getLOAIKH();
            model.addRow(row);
        }

        //    }catch(ArrayIndexOutOfBoundsException ex){
        jTableKhachhang.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

     public Boolean kiemtratk() {
        if (txt_tenkhach.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui long nhap day du thong tin tim kiem", "Thong bao", 2);
            return false;
        }
        return true;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(kiemtratk())
        {
        String sql = "select * from hr.khachhang where tenkh= '" + txt_tenkhach.getText() + "'";//TRAN VAN HUNG 
        String colTieuDe1[] = new String[]{"Mã Khách Hàng", "Tên Khách Hàng", "Ngày Sinh", "Giới Tính", "Chứng Minh Nhân Dân", "Quốc Tịch", "Số Điện Thoại",};
        ArrayList<KhachHang> dskh = layDanhSachKhachHang(sql);

        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dskh.size(); i++) {

            row = new Object[7];

            // GÁN GIÁ TRỊ
            row[0] = dskh.get(i).getMAKH();
            row[1] = dskh.get(i).getTENKH();
            row[2] = dskh.get(i).getNGAYSINH();
            row[3] = dskh.get(i).getGIOITINH();
            row[4] = dskh.get(i).getCMND();
            row[5] = dskh.get(i).getQUOCTICH();
            row[6] = dskh.get(i).getSDT();

            model.addRow(row);
        }

        //    }catch(ArrayIndexOutOfBoundsException ex){
        jTableKhachhang.setModel(model);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        title.clear();
        data.clear();
        title.add("Tên Khách Hàng");
        title.add("Số Phòng");
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "select distinct tenkh , d.sophong\n"
                    + "from hr.khachhang e full outer join hr.thuephong d \n"
                    + "on (e.makh = d.makh)";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                data.add(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        jTableKhachhang.setModel(new DefaultTableModel(data, title));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldLOAIKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLOAIKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLOAIKHActionPerformed

    private void jTextFieldCMNDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCMNDKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCMNDKeyTyped

    private void jTextFieldNGAYSINHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNGAYSINHKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNGAYSINHKeyTyped

    private void jTextFieldMAKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMAKHKeyPressed
        // TODO add your handling code here:
        if(jTextFieldMAKH.getText().length()>=10)
        {
            jTextFieldMAKH.setText((jTextFieldMAKH.getText().substring(0,9)));
        }
    }//GEN-LAST:event_jTextFieldMAKHKeyPressed

    private void jTextFieldGIOITINHKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldGIOITINHKHKeyPressed
        // TODO add your handling code here
    }//GEN-LAST:event_jTextFieldGIOITINHKHKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        title.clear();
        data.clear();
        title.add("Số Lượng KH");
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "select slkhachhang() from dual";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                data.add(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        jTableKhachhang.setModel(new DefaultTableModel(data, title));
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHang_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sapxep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonclear2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableKhachhang;
    private javax.swing.JTextField jTextFieldCMND;
    private javax.swing.JTextField jTextFieldGIOITINHKH;
    private javax.swing.JTextField jTextFieldLOAIKH;
    private javax.swing.JTextField jTextFieldMAKH;
    private javax.swing.JTextField jTextFieldNGAYSINH;
    private javax.swing.JTextField jTextFieldQUOCTICH;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldTENKH;
    private javax.swing.JButton sua1;
    private javax.swing.JButton them1;
    private javax.swing.JButton thoat1;
    private javax.swing.JTextField txt_tenkhach;
    private javax.swing.JButton xoa1;
    // End of variables declaration//GEN-END:variables
}
