package qlks.Form;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import qlks.HoaDon;
import qlks.KhachHang;
import static qlks.MyConnection.getConnection;
import qlks.NhanVien;
import static qlks.Form.DangNhap_Form.Hostname;
import static qlks.Form.DangNhap_Form.Name_Ac;
import static qlks.Form.DangNhap_Form.Password;
import static qlks.Form.DangNhap_Form.Port;
import static qlks.Form.DangNhap_Form.SID;
import static qlks.Form.DangNhap_Form.Username;
import static qlks.Form.DangNhap_Form.check;

public class NhanVien_Form extends javax.swing.JFrame {

    public NhanVien_Form() {
        initComponents();
        getConnection(Hostname, Port, SID, Username, Password);
        jTextFieldMANV.requestFocus();
        hienThiDanhSachNhanVien();
        enable();
        
    }
    Vector title = new Vector();
    Vector data = new Vector();
    Connection con = null;
    Statement st = null;

    ImageIcon icon;

    public  void enable()
    {
        if (check == true && Name_Ac.equals("sys"))
        {
            jButton7.setEnabled(false);
            jButton9.setEnabled(false);
            jButton8.setEnabled(false);
            them.setEnabled(true);
            sua.setEnabled(true);
            xoa.setEnabled(true);
        }
        if (check == true && Name_Ac.equals("hr"))
        {
            jButton7.setEnabled(true);
            jButton9.setEnabled(true);
            jButton8.setEnabled(true);
            them.setEnabled(false);
            sua.setEnabled(false);
            xoa.setEnabled(false);
        }
    }
    private void setLabelImage(String imagePath) {
        if (imagePath == null) {
            imagePath = "null";
        }
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imagePath));
        } catch (IOException e) {
        }
        icon = new ImageIcon(img);

        jLabelHinhAnh.setIcon(icon);
    }

    public ArrayList<NhanVien> layDanhSachNhanVien(String sql) {
        ArrayList<NhanVien> dsnv = new ArrayList<NhanVien>();
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            // Thưcj thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            NhanVien nv;
            while (rs.next()) {
                nv = new NhanVien(rs.getString("MANV"), rs.getString("TENNV"), rs.getString("CHUCVU"),
                         rs.getInt("LUONGNV"), rs.getDate("NGAYSINH"), 
                        rs.getString("GIOITINH"), rs.getString("MANQL"), rs.getString("ANHNV"));

                //Thêm vào danh sách
                dsnv.add(nv);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        return dsnv;
    }

    public void hienThiDanhSachNhanVien() {

        String colTieuDe1[] = new String[]{"Mã Nhân Viên", "Tên Nhân Viên", "Chức Vụ", "Lương", "Ngày Sinh", "Giới Tính", "Mã NQL", "Ảnh NV"};
        String sql = "select * from hr.nhanvien";
        ArrayList<NhanVien> dsnv = layDanhSachNhanVien(sql);
        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dsnv.size(); i++) {

            row = new Object[8];

            // GÁN GIÁ TRỊ
            row[0] = dsnv.get(i).getMANV();
            row[1] = dsnv.get(i).getTENNV();
            row[2] = dsnv.get(i).getCHUCVU();
            row[3] = dsnv.get(i).getLUONGNV();
            row[4] = dsnv.get(i).getNGAYSINH();
            row[5] = dsnv.get(i).getGIOITINH();
            row[6] = dsnv.get(i).getMANQL();
            row[7] = dsnv.get(i).getANHNV();

            model.addRow(row);
        }

        //    }catch(ArrayIndexOutOfBoundsException ex){
        jTableNhanvien.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhanvien = new javax.swing.JTable();
        btn_sapxep = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMANV = new javax.swing.JTextField();
        jTextFieldTENNV = new javax.swing.JTextField();
        jTextFieldCHUCVU = new javax.swing.JTextField();
        jTextFieldLUONG = new javax.swing.JTextField();
        jTextFieldNGAYSINH = new javax.swing.JTextField();
        jTextFieldGIOITINH = new javax.swing.JTextField();
        them = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        thoat = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMANQL = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextFieldANHNV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jTextFieldPHANTRAM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabelHinhAnh = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTKnhanvien = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/nhanvien.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jTableNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNhanvien);

        btn_sapxep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/sapxep.png"))); // NOI18N
        btn_sapxep.setText("Sắp Xếp");
        btn_sapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sapxepActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/timkiem.png"))); // NOI18N
        jButton1.setText("NV Quản Lý");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/xemphong.png"))); // NOI18N
        jButton2.setText("Nhân Viên & NQL của nhân viên");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Nhân Viên"));

        jLabel2.setText("Mã Nhân Viên");

        jLabel3.setText("Tên Nhân Viên");

        jLabel4.setText("Chức Vụ");

        jLabel5.setText("Lương");

        jLabel6.setText("Ngày Sinh");

        jLabel7.setText("Giới Tính");

        jTextFieldMANV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMANVKeyPressed(evt);
            }
        });

        jTextFieldTENNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTENNVActionPerformed(evt);
            }
        });

        jTextFieldLUONG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLUONGActionPerformed(evt);
            }
        });
        jTextFieldLUONG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLUONGKeyTyped(evt);
            }
        });

        them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/THEM.png"))); // NOI18N
        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/SUA.png"))); // NOI18N
        sua.setText("Sửa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/XOA.png"))); // NOI18N
        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/THOAT.png"))); // NOI18N
        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        jButtonclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/CLEAR.png"))); // NOI18N
        jButtonclear.setText("Clear");
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });

        jLabel8.setText("Mã NQL");

        jTextFieldMANQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldMANQLMouseClicked(evt);
            }
        });
        jTextFieldMANQL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMANQLKeyPressed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/anhnv.png"))); // NOI18N
        jButton4.setText("ảnh NV");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Ảnh");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tăng Lương Nhân Viên"));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/Knob-Refresh-icon.png"))); // NOI18N
        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel11.setText("Số %");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPHANTRAM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPHANTRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldCHUCVU, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTENNV)
                                    .addComponent(jTextFieldLUONG, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMANV)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMANQL, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldGIOITINH, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldNGAYSINH)
                                    .addComponent(jTextFieldANHNV)))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(thoat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(them)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sua)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMANV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTENNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCHUCVU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldLUONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNGAYSINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldGIOITINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMANQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldANHNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sua)
                    .addComponent(them)
                    .addComponent(jButtonclear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xoa)
                    .addComponent(thoat)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton8.setText("Xem Proc");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHinhAnh)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabelHinhAnh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        jLabel10.setText("Mã NV");

        jTextFieldTKnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTKnhanvienActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/timkiem.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addComponent(jTextFieldTKnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTKnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/xemphong.png"))); // NOI18N
        jButton9.setText("Tổng Lương");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sapxep))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton9)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_sapxep)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1)
                                    .addComponent(jButton9))))))
                .addContainerGap())
        );

        jButton5.setText("Cursor Lương");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Thêm NV(mã tự động)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(530, 530, 530)
                    .addComponent(jButton3)
                    .addContainerGap(640, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(556, 556, 556)
                    .addComponent(jButton5)
                    .addContainerGap(666, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(247, 247, 247)
                    .addComponent(jButton3)
                    .addContainerGap(270, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(247, 247, 247)
                    .addComponent(jButton5)
                    .addContainerGap(270, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNhanvienMouseClicked

        // TODO add your handling code here:
        int i = jTableNhanvien.getSelectedRow();
        TableModel model = jTableNhanvien.getModel();

        if (jTextFieldMANQL.getText().isEmpty()) {
            jTextFieldMANQL.setText("");
        }
        jTextFieldMANV.setText(model.getValueAt(i, 0).toString());
        jTextFieldTENNV.setText(model.getValueAt(i, 1).toString());
        jTextFieldCHUCVU.setText(model.getValueAt(i, 2).toString());
        jTextFieldLUONG.setText(model.getValueAt(i, 3).toString());
        jTextFieldNGAYSINH.setText(model.getValueAt(i, 4).toString());
        jTextFieldGIOITINH.setText(model.getValueAt(i, 5).toString());
        jTextFieldANHNV.setText(model.getValueAt(i, 7).toString());
        try {
            jTextFieldMANQL.setText(model.getValueAt(i, 6).toString());
        } catch (Exception e) {
            jTextFieldMANQL.setText("");
        }
    }//GEN-LAST:event_jTableNhanvienMouseClicked

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
        // TODO add your handling code here:
        jTextFieldMANV.setRequestFocusEnabled(true);
        jTextFieldMANV.requestFocus();
        jTextFieldMANV.setText("");
        jTextFieldTENNV.setText("");
        jTextFieldANHNV.setText("");
        jTextFieldCHUCVU.setText("");
        jTextFieldLUONG.setText("");
        jTextFieldNGAYSINH.setText("");
        jTextFieldGIOITINH.setText("");
        jTextFieldMANQL.setText("");
        hienThiDanhSachNhanVien();
    }//GEN-LAST:event_jButtonclearActionPerformed

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatActionPerformed
        // TODO add your handling code here:
        thoat.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát chương"
                + " trình không", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_thoatActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
        int pos = jTableNhanvien.getSelectedRow();
        if (pos < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn Hãy Chọn 1 dòng");
        }
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            // Tạo một đối tượng để thực hiện công việc
            st = (Statement) con.createStatement();
            String query = "DELETE FROM hr.NhanVien WHERE MANV = '" + jTextFieldMANV.getText() + "'";
            st.executeUpdate(query);
            System.out.print(query);
            hienThiDanhSachNhanVien();

        } catch (Exception ex) {

            ex.printStackTrace();
        }
    }//GEN-LAST:event_xoaActionPerformed
    public Boolean kiemtrangaysinh() {
        try {
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            Date date = df.parse(jTextFieldNGAYSINH.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập kiểu dữ liệu ngày sinh là dd/mm/yyyy", "Thong bao", 2);
            return false;
        }
        return true;
    }

    public Boolean kiemtratxt() {
        if (jTextFieldMANV.getText().equals("") || jTextFieldTENNV.getText().equals("") || jTextFieldCHUCVU.getText().equals("") || jTextFieldLUONG.getText().equals("") || jTextFieldGIOITINH.getText().equals("")
                || jTextFieldMANQL.getText().equals("") || jTextFieldANHNV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Thong bao", 2);
            return false;
        }
        return true;
    }
    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        int pos = jTableNhanvien.getSelectedRow();
        if (pos < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn Hãy Chọn 1 dòng");
        } else {
            try {
                if (kiemtratxt() && ktragioitinh()) {
                    // Tạo một đối tượng để thực hiện công việc
                    int i = -1;
                    st = (Statement) con.createStatement();
                    String query = "update hr.nhanvien set anhnv='" + jTextFieldANHNV.getText() 
                            + "' ,tennv='" + jTextFieldTENNV.getText() + "',chucvu='"
                            + jTextFieldCHUCVU.getText() + "',luongnv='" + jTextFieldLUONG.getText() + "',ngaysinh=TO_DATE('"
                            + jTextFieldNGAYSINH.getText() + "','YYYY/MM/DD'),gioitinh='" + jTextFieldGIOITINH.getText()
                            + "',manql='" + jTextFieldMANQL.getText() + "' where manv='" + jTextFieldMANV.getText() + "'";
                    System.out.print(query);
                    i = st.executeUpdate(query);
                    if (i != -1) {
                        hienThiDanhSachNhanVien();
                    }
                }

            } catch (Exception ex) {

                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_suaActionPerformed

    ArrayList<NhanVien> dsnv = layDanhSachNhanVien("select * from hr.nhanvien");

    public static Boolean kiemtramanv(ArrayList<NhanVien> dsnv, String manv) {
        for (NhanVien t : dsnv) {
            if (t.getMANV().equals(manv)) {
                return true;
            }
        }
        return false;
    }

    public Boolean kiemtramanhanvien() {
        if (kiemtramanv(dsnv, jTextFieldMANV.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Mã Nhân Viên Khác!!", "Thong bao", 2);
            return false;
        }
        return true;
    }

    public boolean ktragioitinh() {
        if (jTextFieldGIOITINH.getText().toString().equals("NAM")
                || jTextFieldGIOITINH.getText().toString().equals("NU")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập lại giới tính là NAM or NU!!", "Thong bao", 2);
            return false;
        }
    }
    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        if (kiemtrangaysinh() && kiemtratxt() && kiemtramanhanvien() && ktragioitinh()) {
            Connection con = getConnection(Hostname, Port, SID, Username, Password);
            try {
                // Tạo một đối tượng để thực hiện công việc
                st = (Statement) con.createStatement();
                String query = "INSERT INTO hr.NhanVien VALUES('" + jTextFieldMANV.getText() + "',"
                        + "'" + jTextFieldTENNV.getText() + "','" + jTextFieldCHUCVU.getText() + "',"
                        + jTextFieldLUONG.getText() + ",TO_DATE('" + jTextFieldNGAYSINH.getText()
                        + "','DD/MM/YYYY'),'" + jTextFieldGIOITINH.getText() + "','" 
                        + jTextFieldMANQL.getText() + "','" + jTextFieldANHNV.getText() + "')";
                System.out.print(query);
                st.execute(query);
                hienThiDanhSachNhanVien();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_themActionPerformed

    private void jTextFieldLUONGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLUONGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLUONGActionPerformed

    private void jTextFieldTENNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTENNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTENNVActionPerformed

    private void btn_sapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sapxepActionPerformed
        // TODO add your handling code here:
        String colTieuDe1[] = new String[]{"Mã Nhân Viên", "Tên Nhân Viên", "Chức Vụ", "Lương", "Ngày Sinh", "Giới Tính", "Mã NQL", "Ảnh Nhân Viên"};
        String sql = "select * from hr.nhanvien order by 3";
        ArrayList<NhanVien> dsnv = layDanhSachNhanVien(sql);
        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dsnv.size(); i++) {

            row = new Object[8];

            // GÁN GIÁ TRỊ
            row[0] = dsnv.get(i).getMANV();
            row[1] = dsnv.get(i).getTENNV();
            row[2] = dsnv.get(i).getCHUCVU();
            row[3] = dsnv.get(i).getLUONGNV();
            row[4] = dsnv.get(i).getNGAYSINH();
            row[5] = dsnv.get(i).getGIOITINH();
            row[6] = dsnv.get(i).getMANQL();
            row[7] = dsnv.get(i).getANHNV();
            model.addRow(row);
        }

        //    }catch(ArrayIndexOutOfBoundsException ex){
        jTableNhanvien.setModel(model);
    }//GEN-LAST:event_btn_sapxepActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String colTieuDe1[] = new String[]{"Mã Nhân Viên", "Tên Nhân Viên", "Chức Vụ", "Lương", "Ngày Sinh", "Giới Tính"};
        String sql = "select * from hr.nhanvien where chucvu='QUAN LY'";
        ArrayList<NhanVien> dsnv = layDanhSachNhanVien(sql);
        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dsnv.size(); i++) {

            row = new Object[6];

            // GÁN GIÁ TRỊ
            row[0] = dsnv.get(i).getMANV();
            row[1] = dsnv.get(i).getTENNV();
            row[2] = dsnv.get(i).getCHUCVU();
            row[3] = dsnv.get(i).getLUONGNV();
            row[4] = dsnv.get(i).getNGAYSINH();
            row[5] = dsnv.get(i).getGIOITINH();

            model.addRow(row);
        }

        //    }catch(ArrayIndexOutOfBoundsException ex){
        jTableNhanvien.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        title.clear();
        data.clear();
        title.add("Tên Nhân VIên");
        title.add("Chức Vụ");
        title.add("Người Quản Lí");
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "SELECT C1.TENNV, C1.CHUCVU, C2.TENNV AS NQL\n"
                    + "FROM hr.NHANVIEN C1 JOIN hr.NHANVIEN C2 \n"
                    + "ON C1.MANQL = C2.MANV";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                data.add(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        jTableNhanvien.setModel(new DefaultTableModel(data, title));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int pos = jTableNhanvien.getSelectedRow();
        if (pos < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn Hãy Chọn 1 Nhân Viên");
            return;
        }
        String imagePath = "C:\\Users\\Dell\\Desktop\\Oracle_DoAn_QLKS\\QLKS\\AnhNV\\" + jTextFieldANHNV.getText();
        setLabelImage(imagePath);
    }//GEN-LAST:event_jButton4ActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            // Tạo một đối tượng để thực hiện công việc
            st = (Statement) con.createStatement();
            String query = "INSERT INTO hr.NhanVien VALUES(MANV.NEXTVAL,"
                    + "'" + jTextFieldTENNV.getText() + "','" + jTextFieldCHUCVU.getText() + "',"
                    + jTextFieldLUONG.getText() + ",'" + jTextFieldNGAYSINH.getText()
                    + "','" + jTextFieldGIOITINH.getText() + "','" + jTextFieldMANQL.getText() + "','" + jTextFieldANHNV.getText() + "')";
            System.out.print(query);
            st.execute(query);
            hienThiDanhSachNhanVien();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        title.clear();
        data.clear();
        title.add("Luong");
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql1 = "CREATE OR REPLACE FUNCTION func \n"
                    + "  RETURN number  \n"
                    + "IS \n"
                    + "   cnumber number;  \n"
                    + "CURSOR c1  \n"
                    + "   IS \n"
                    + "     SELECT luongnv  \n"
                    + "     FROM hr.nhanvien ;\n"
                    + "BEGIN \n"
                    + "OPEN c1;  \n"
                    + "   FETCH c1 INTO cnumber;  \n"
                    + "IF c1%notfound THEN \n"
                    + "      cnumber := 3000000;  \n"
                    + " END IF;  \n"
                    + "CLOSE c1;  \n"
                    + "RETURN cnumber;  \n"
                    + "END;";
            String sql2 = "SELECT func()\n"
                    + "from hr.nhanvien";
            System.out.print(sql1);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs1 = st.executeQuery(sql1);
            ResultSet rs2 = st.executeQuery(sql2);
            while (rs2.next()) {
                Vector v = new Vector();
                v.add(rs2.getString(1));
                data.add(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        jTableNhanvien.setModel(new DefaultTableModel(data, title));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldLUONGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLUONGKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldLUONGKeyTyped

    private void jTextFieldMANVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMANVKeyPressed
        // TODO add your handling code here:
        if (jTextFieldMANV.getText().length() >= 10) {
            jTextFieldMANV.setText((jTextFieldMANV.getText().substring(0, 9)));
        }
    }//GEN-LAST:event_jTextFieldMANVKeyPressed

    private void jTextFieldMANQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMANQLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMANQLMouseClicked

    private void jTextFieldMANQLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMANQLKeyPressed
        // TODO add your handling code here:
        if (jTextFieldMANQL.getText().length() >= 10) {
            jTextFieldMANQL.setText((jTextFieldMANQL.getText().substring(0, 9)));
        }
    }//GEN-LAST:event_jTextFieldMANQLKeyPressed

    private void jTextFieldTKnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTKnhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTKnhanvienActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        String colTieuDe1[] = new String[]{"Mã Nhân Viên", "Tên Nhân Viên", "Chức Vụ", "Lương", "Ngày Sinh", "Giới Tính", "Mã NQL", "Ảnh NV"};
        String sql = "select * from hr.nhanvien where manv='" + jTextFieldTKnhanvien.getText() + "'";
        ArrayList<NhanVien> dsnv = layDanhSachNhanVien(sql);
        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dsnv.size(); i++) {

            row = new Object[8];

            // GÁN GIÁ TRỊ
            row[0] = dsnv.get(i).getMANV();
            row[1] = dsnv.get(i).getTENNV();
            row[2] = dsnv.get(i).getCHUCVU();
            row[3] = dsnv.get(i).getLUONGNV();
            row[4] = dsnv.get(i).getNGAYSINH();
            row[5] = dsnv.get(i).getGIOITINH();
            row[6] = dsnv.get(i).getMANQL();
            row[7] = dsnv.get(i).getANHNV();

            model.addRow(row);
        }

        //    }catch(ArrayIndexOutOfBoundsException ex){
        jTableNhanvien.setModel(model);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        int pos = jTableNhanvien.getSelectedRow();
        if (pos < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn Hãy Chọn 1 nhân viên");
        } else {
            if (jTextFieldPHANTRAM.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Nhập Số %!!");
            } else {
                try {
                    st = (Statement) con.createStatement();
                    String sql = "execute Tang_Luong('"+jTextFieldMANV.getText()+"',"+ jTextFieldPHANTRAM.getText() +")";
                    System.out.print(sql);
                    // Thưc thi câu lệnh truy vấn
                    ResultSet rs = st.executeQuery(sql);
                    JOptionPane.showMessageDialog(rootPane, "Thành Công");
                    hienThiDanhSachNhanVien();
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Thất Bại");
                }
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        title.clear();
        data.clear();
        title.add("Text");
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "select text FROM user_source where name='Tang_Luong' and type='PROCEDURE' order by line";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                data.add(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }

        jTableNhanvien.setModel(new DefaultTableModel(data, title));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        title.clear();
        data.clear();
        title.add("Tổng Lương NV");
        Connection con = getConnection(Hostname, Port, SID, Username, Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "select sum_luongnv() from dual";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                data.add(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        jTableNhanvien.setModel(new DefaultTableModel(data, title));
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVien_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sapxep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonclear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHinhAnh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableNhanvien;
    private javax.swing.JTextField jTextFieldANHNV;
    private javax.swing.JTextField jTextFieldCHUCVU;
    private javax.swing.JTextField jTextFieldGIOITINH;
    private javax.swing.JTextField jTextFieldLUONG;
    private javax.swing.JTextField jTextFieldMANQL;
    private javax.swing.JTextField jTextFieldMANV;
    private javax.swing.JTextField jTextFieldNGAYSINH;
    private javax.swing.JTextField jTextFieldPHANTRAM;
    private javax.swing.JTextField jTextFieldTENNV;
    private javax.swing.JTextField jTextFieldTKnhanvien;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton sua;
    private javax.swing.JButton them;
    private javax.swing.JButton thoat;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables

}
