
package qlks.Form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import qlks.HoaDon;
import static qlks.MyConnection.getConnection;
import qlks.NhanVien;
import qlks.Phong;
import static qlks.Form.DangNhap_Form.Hostname;
import static qlks.Form.DangNhap_Form.Name_Ac;
import static qlks.Form.DangNhap_Form.Password;
import static qlks.Form.DangNhap_Form.Port;
import static qlks.Form.DangNhap_Form.SID;
import static qlks.Form.DangNhap_Form.Username;
import static qlks.Form.DangNhap_Form.check;


public class Phong_Form extends javax.swing.JFrame {

    public Phong_Form() {
        initComponents();
        getConnection(Hostname,Port,SID,Username,Password);
        hienThiDanhSachPhong();
        enable();
    }
    Vector title = new Vector();
    Vector data = new Vector();
    Connection con = null;
    Statement st = null;

    public void enable()
    {
        System.out.println(Name_Ac);
        if (check == true && Name_Ac.equals("hr"));
        {them3.setEnabled(false);
        sua3.setEnabled(false);
        xoa3.setEnabled(false);}

        if (check == true && Name_Ac.equals("scott"));
        {them3.setEnabled(false);
        sua3.setEnabled(false);
        xoa3.setEnabled(false);}
        if (check == true && Name_Ac.equals("sys")) {
           them3.setEnabled(true);
        sua3.setEnabled(true);
        xoa3.setEnabled(true);
        }
    }
    public ArrayList<Phong> layDanhSachPhong(String sql) {
        ArrayList<Phong> dsp = new ArrayList<Phong>();
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();

            // Thưcj thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            Phong p;
            while (rs.next()) {
                p = new Phong(rs.getString("SOPHONG"), rs.getString("LOAIPHONG"), rs.getInt("GIAPHONG"), rs.getString("TINHTRANG"));

                //Thêm vào danh sách
                dsp.add(p);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        return dsp;
    }

    public void hienThiDanhSachPhong() {
        String colTieuDe1[] = new String[]{"Số Phòng", "Loại Phòng", "Giá Phòng", "Tình Trạng"};
        String sql = "SELECT * FROM hr.phong";
        ArrayList<Phong> dsp = layDanhSachPhong(sql);

        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dsp.size(); i++) {

            row = new Object[4];

            // GÁN GIÁ TRỊ
            row[0] = dsp.get(i).getSOPHONG();
            row[1] = dsp.get(i).getLOAIPHONG();
            row[2] = dsp.get(i).getGIAPHONG();
            row[3] = dsp.get(i).getTINHTRANG();

            model.addRow(row);
        }

        //}catch(ArrayIndexOutOfBoundsException ex){
        jTablePHONG.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePHONG = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldSOPHONG = new javax.swing.JTextField();
        jTextFieldLOAIPHONG = new javax.swing.JTextField();
        jTextFieldGIAPHONG = new javax.swing.JTextField();
        jTextFieldTINHTRANG = new javax.swing.JTextField();
        them3 = new javax.swing.JButton();
        sua3 = new javax.swing.JButton();
        xoa3 = new javax.swing.JButton();
        thoat3 = new javax.swing.JButton();
        jButtonclear3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_tenph = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_sapxep = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_sapxep1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/qqqqq.png"))); // NOI18N
        jLabel22.setText("QUẢN LÝ PHÒNG");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
        );

        jTablePHONG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePHONG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePHONGMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTablePHONG);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Phòng"));

        jLabel23.setText("Số Phòng");

        jLabel25.setText("Loại Phòng");

        jLabel26.setText("Giá Phòng");

        jLabel28.setText("Tình Trạng");

        jTextFieldSOPHONG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSOPHONGKeyPressed(evt);
            }
        });

        jTextFieldGIAPHONG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldGIAPHONGKeyTyped(evt);
            }
        });

        jTextFieldTINHTRANG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTINHTRANGKeyTyped(evt);
            }
        });

        them3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/THEM.png"))); // NOI18N
        them3.setText("Thêm");
        them3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them3ActionPerformed(evt);
            }
        });

        sua3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/SUA.png"))); // NOI18N
        sua3.setText("Sửa");
        sua3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua3ActionPerformed(evt);
            }
        });

        xoa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/XOA.png"))); // NOI18N
        xoa3.setText("Xóa");
        xoa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa3ActionPerformed(evt);
            }
        });

        thoat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/THOAT.png"))); // NOI18N
        thoat3.setText("Thoát");
        thoat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoat3ActionPerformed(evt);
            }
        });

        jButtonclear3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/CLEAR.png"))); // NOI18N
        jButtonclear3.setText("Clear");
        jButtonclear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclear3ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Phòng"));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/timkiem.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Số Phòng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_tenph, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23)
                        .addComponent(jLabel25)
                        .addComponent(jLabel26))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(4, 4, 4)))
                .addGap(23, 23, 23)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldGIAPHONG)
                    .addComponent(jTextFieldTINHTRANG)
                    .addComponent(jTextFieldLOAIPHONG)
                    .addComponent(jTextFieldSOPHONG))
                .addContainerGap())
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them3)
                    .addComponent(xoa3))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thoat3)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(sua3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonclear3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldSOPHONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldLOAIPHONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldGIAPHONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldTINHTRANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them3)
                    .addComponent(sua3)
                    .addComponent(jButtonclear3))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xoa3)
                    .addComponent(thoat3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_sapxep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/sapxep.png"))); // NOI18N
        btn_sapxep.setText("Sắp Xếp");
        btn_sapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sapxepActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/xemphong.png"))); // NOI18N
        jButton1.setText("khách Hàng(thuê > 2 phòng)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/xemphong.png"))); // NOI18N
        jButton3.setText("Phòng(người đặt >2)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_sapxep1.setBackground(new java.awt.Color(204, 204, 255));
        btn_sapxep1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_sapxep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/timkiem.png"))); // NOI18N
        btn_sapxep1.setText("Phòng Còn Trống");
        btn_sapxep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sapxep1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_sapxep1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sapxep)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sapxep))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sapxep1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)))
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePHONGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePHONGMouseClicked
        // TODO add your handling code here:
        int i = jTablePHONG.getSelectedRow();
        TableModel model = jTablePHONG.getModel();
        jTextFieldSOPHONG.setText(model.getValueAt(i, 0).toString());
        jTextFieldLOAIPHONG.setText(model.getValueAt(i, 1).toString());
        jTextFieldGIAPHONG.setText(model.getValueAt(i, 2).toString());
        jTextFieldTINHTRANG.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jTablePHONGMouseClicked

    private void jButtonclear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclear3ActionPerformed
        // TODO add your handling code here:
        jTextFieldSOPHONG.setText("");
        jTextFieldLOAIPHONG.setText("");
        jTextFieldGIAPHONG.setText("");
        jTextFieldTINHTRANG.setText("");
        jTextFieldSOPHONG.requestFocus();
        hienThiDanhSachPhong();
    }//GEN-LAST:event_jButtonclear3ActionPerformed

    private void thoat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoat3ActionPerformed
        // TODO add your handling code here:
        thoat3.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát chương"
                + " trình không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_thoat3ActionPerformed

    public ArrayList<HoaDon> layDanhSachHoaDon(String sql) {
        ArrayList<HoaDon> dshd = new ArrayList<HoaDon>();
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();

            // Thưcj thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            HoaDon hd;
            while (rs.next()) {
                hd = new HoaDon(rs.getString("MAHD"), rs.getString("TENHD"), rs.getString("MADV"), rs.getString("MAKH"), rs.getDate("NGAYLAP"), rs.getString("MANV"),rs.getString("SOPHONG"));

                //Thêm vào danh sách
                dshd.add(hd);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        return dshd;
    }
    ArrayList<HoaDon> dshd = layDanhSachHoaDon("select * from hr.HoaDon");
    public static Boolean kiemtrathd(ArrayList<HoaDon> dshd,String sop) {
        for (HoaDon c : dshd) {
            if (c.getSOPHONG().equals(sop)) {
                return true;
            }
        }
        return false;
    }
    public Boolean kiemtrathuehd() {
        if (kiemtrathd(dshd, jTextFieldSOPHONG.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Phòng này đang được Thuê, không xóa được!!", "Thong bao", 2);
            return true;
        }
        return false;
    }
    private void xoa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoa3ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        if(kiemtrathuehd()==false)
        {
        try {
            // Tạo một đối tượng để thực hiện công việc
            st = (Statement) con.createStatement();
            String query = "DELETE FROM hr.phong WHERE SOPHONG = '" + jTextFieldSOPHONG.getText() + "'";
            st.executeUpdate(query);
            hienThiDanhSachPhong();

        } catch (Exception ex) {

            ex.printStackTrace();
        }
        }
    }//GEN-LAST:event_xoa3ActionPerformed

    private void sua3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua3ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        int pos = jTablePHONG.getSelectedRow();
        if (pos < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn Hãy Chọn 1 dòng");
        } else {
            try {
                if (kiemtratxt()&& ktratinhtrang()) {
                    // Tạo một đối tượng để thực hiện công việc
                    int i = -1;
                    st = (Statement) con.createStatement();
                    String query = "update hr.phong set loaiphong='" + jTextFieldLOAIPHONG.getText()
                            + "', giaphong=" + jTextFieldGIAPHONG.getText() + ", tinhtrang='" + jTextFieldTINHTRANG.getText()
                            + "' where sophong='" + jTextFieldSOPHONG.getText() + "'";
                    System.out.print(query);
                    i = st.executeUpdate(query);
                    if (i != -1) {
                        hienThiDanhSachPhong();
                    }
                }

            } catch (Exception ex) {

                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_sua3ActionPerformed
    public boolean  ktratinhtrang()
    {
        if(jTextFieldTINHTRANG.getText().toString().equals("DA DAT")
                ||jTextFieldTINHTRANG.getText().toString().equals("CON TRONG"))
        {
            return  true;
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập tình trạng là DA DAT or CON TRONG!!", "Thong bao", 2);
           return  false;
        }
    }
    public Boolean kiemtratxt() {
        if (jTextFieldSOPHONG.getText().equals("") || jTextFieldLOAIPHONG.getText().equals("")
                || jTextFieldGIAPHONG.getText().equals("") || jTextFieldTINHTRANG.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!!", "Thong bao", 2);
            return false;
        }
        return true;
    }
     ArrayList<Phong> dsp = layDanhSachPhong("select * from hr.phong");

    public static Boolean kiemtrasop(ArrayList<Phong> dsp, String sop) {
        for (Phong t : dsp) {
            if (t.getSOPHONG().equals(sop)) {
                return true;
            }
        }
        return false;
    }

    public Boolean kiemtrasophong() {
        if (kiemtrasop(dsp, jTextFieldSOPHONG.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Số Phòng Khác!!", "Thong bao", 2);
            return false;
        }
        return true;
    }
    private void them3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them3ActionPerformed
        // TODO add your handling code here
        if (kiemtratxt()&&kiemtrasophong()&& ktratinhtrang()) {
            Connection con = getConnection(Hostname,Port,SID,Username,Password);
            try {
                // Tạo một đối tượng để thực hiện công việc
                st = (Statement) con.createStatement();
                String query = "INSERT INTO hr.phong VALUES('" + jTextFieldSOPHONG.getText() + "',"
                        + "'" + jTextFieldLOAIPHONG.getText() + "', " + jTextFieldGIAPHONG.getText()
                        + ", '" + jTextFieldTINHTRANG.getText() + "')";

                st.execute(query);
                hienThiDanhSachPhong();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_them3ActionPerformed

    private void btn_sapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sapxepActionPerformed
        // TODO add your handling code here:
        String colTieuDe1[] = new String[]{"Số Phòng", "Loại Phòng", "Giá Phòng", "Tình Trạng"};
        String sql = "select * from hr.phong order by 2";
        ArrayList<Phong> dsp = layDanhSachPhong(sql);

        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dsp.size(); i++) {

            row = new Object[4];

            // GÁN GIÁ TRỊ
            row[0] = dsp.get(i).getSOPHONG();
            row[1] = dsp.get(i).getLOAIPHONG();
            row[2] = dsp.get(i).getGIAPHONG();
            row[3] = dsp.get(i).getTINHTRANG();

            model.addRow(row);
        }

        //}catch(ArrayIndexOutOfBoundsException ex){
        jTablePHONG.setModel(model);
    }//GEN-LAST:event_btn_sapxepActionPerformed

     public Boolean kiemtratk() {
        if (txt_tenph.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui long nhap day du thong tin tim kiem", "Thong bao", 2);
            return false;
        }
        return true;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(kiemtratk())
        {
        title.clear();
        data.clear();
        title.add("Số Phòng");
        title.add("Loại Phòng");
        title.add("Giá Phòng");
        title.add("Tình Trạng");
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "select * from hr.phong where sophong='" + txt_tenph.getText() + "'";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                data.add(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        jTablePHONG.setModel(new DefaultTableModel(data, title));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        title.clear();
        data.clear();
        title.add("Mã khách hàng");
        title.add("Tên Khách Hàng");
        title.add("Số Phòng Thuê");
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "select t.makh,k.tenkh,count(sophong)\n"
                    + "from hr.thuephong t join hr.khachhang k\n"
                    + "on t.makh = k.makh\n"
                    + "group by t.makh,k.tenkh\n"
                    + "having count(sophong)>1";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                data.add(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        jTablePHONG.setModel(new DefaultTableModel(data, title));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        title.clear();
        data.clear();
        title.add("Số Phòng Thuê");
        title.add("Số Người ở");
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "select sophong,count(makh)\n"
                    + "from hr.thuephong\n"
                    + "group by sophong\n"
                    + "having count(makh)>1";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                data.add(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        jTablePHONG.setModel(new DefaultTableModel(data, title));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_sapxep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sapxep1ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from hr.phong where tinhtrang='CON TRONG'";
        String colTieuDe1[] = new String[]{"Số Phòng", "Loại Phòng", "Giá Phòng", "Tình Trạng"};
        ArrayList<Phong> dsp = layDanhSachPhong(sql);

        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dsp.size(); i++) {

            row = new Object[4];

            // GÁN GIÁ TRỊ
            row[0] = dsp.get(i).getSOPHONG();
            row[1] = dsp.get(i).getLOAIPHONG();
            row[2] = dsp.get(i).getGIAPHONG();
            row[3] = dsp.get(i).getTINHTRANG();

            model.addRow(row);
        }

        //}catch(ArrayIndexOutOfBoundsException ex){
        jTablePHONG.setModel(model);
    }//GEN-LAST:event_btn_sapxep1ActionPerformed

    private void jTextFieldTINHTRANGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTINHTRANGKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldTINHTRANGKeyTyped

    private void jTextFieldGIAPHONGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldGIAPHONGKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldGIAPHONGKeyTyped

    private void jTextFieldSOPHONGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSOPHONGKeyPressed
        // TODO add your handling code here:
        if(jTextFieldSOPHONG.getText().length()>=10)
        {
            jTextFieldSOPHONG.setText((jTextFieldSOPHONG.getText().substring(0,9)));
        }
    }//GEN-LAST:event_jTextFieldSOPHONGKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Phong_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Phong_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Phong_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Phong_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phong_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sapxep;
    private javax.swing.JButton btn_sapxep1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonclear3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTablePHONG;
    private javax.swing.JTextField jTextFieldGIAPHONG;
    private javax.swing.JTextField jTextFieldLOAIPHONG;
    private javax.swing.JTextField jTextFieldSOPHONG;
    private javax.swing.JTextField jTextFieldTINHTRANG;
    private javax.swing.JButton sua3;
    private javax.swing.JButton them3;
    private javax.swing.JButton thoat3;
    private javax.swing.JTextField txt_tenph;
    private javax.swing.JButton xoa3;
    // End of variables declaration//GEN-END:variables
}
