/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks.Form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import qlks.CThoadon;
import qlks.DichVu;
import qlks.KhachHang;
import static qlks.MyConnection.getConnection;
import qlks.NhanVien;
import qlks.Phong;
import static qlks.Form.DangNhap_Form.Hostname;
import static qlks.Form.DangNhap_Form.Password;
import static qlks.Form.DangNhap_Form.Port;
import static qlks.Form.DangNhap_Form.SID;
import static qlks.Form.DangNhap_Form.Username;
import qlks.thuephong;

/**
 *
 */
public class QLThuePhong_Form extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiThuePhong
     */
    

    public QLThuePhong_Form() {
        initComponents();
        getConnection(Hostname,Port,SID,Username,Password);
        hienThiDanhSachTP();
        setLocationRelativeTo(null);
    }
    Vector title = new Vector();
    Vector data = new Vector();
    Connection con = null;
    Statement st = null;
    
    public ArrayList<thuephong> layDanhSachTP(String sql) {
        ArrayList<thuephong> d = new ArrayList<thuephong>();
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();

            // Thưcj thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            thuephong w;
            while (rs.next()) {
                w = new thuephong(rs.getString("MADK"), rs.getString("MAKH"), rs.getString("SOPHONG"), 
                rs.getDate("NGAYDK"), rs.getDate("NGAYDI"), rs.getInt("SONGAY"));
                //Thêm vào danh sách
                d.add(w);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        return d;
    }
    
    public void hienThiDanhSachTP() {
        String colTieuDe1[] = new String[]{"Mã Đăng Kí", "Mã Khách", "Số Phòng", "Ngày Đăng Kí", "Ngày Đi", "Số Ngày"};
        String sql = "select * from hr.thuephong";
        ArrayList<thuephong> d = layDanhSachTP(sql);

        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < d.size(); i++) {

            row = new Object[6];

            // GÁN GIÁ TRỊ
            row[0] = d.get(i).getMADK();
            row[1] = d.get(i).getMAKH();
            row[2] = d.get(i).getSOPHONG();
            row[3] = d.get(i).getNGAYDK();
            row[4] = d.get(i).getNGAYDI();
            row[5] = d.get(i).getSONGAY();
            model.addRow(row);
        }

        //}catch(ArrayIndexOutOfBoundsException ex){
        jTableTHUEPHONG.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTHUEPHONG = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldMADK = new javax.swing.JTextField();
        jTextFieldMAKH = new javax.swing.JTextField();
        jTextFieldSOPHONG = new javax.swing.JTextField();
        jTextFieldNGAYDK = new javax.swing.JTextField();
        jTextFieldNGAYDI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSONGAY = new javax.swing.JTextField();
        them4 = new javax.swing.JButton();
        sua4 = new javax.swing.JButton();
        jButtonclear4 = new javax.swing.JButton();
        thoat4 = new javax.swing.JButton();
        xoa4 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/Knob-Loop-On-icon.png"))); // NOI18N
        jButton1.setText("Cập Nhật Lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/tinhtoan.png"))); // NOI18N
        jButton2.setText("Tính Số Ngày");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTableTHUEPHONG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableTHUEPHONG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTHUEPHONGMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTHUEPHONG);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông Tin Quản Lý"));

        jTextFieldMADK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMADKActionPerformed(evt);
            }
        });
        jTextFieldMADK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMADKKeyPressed(evt);
            }
        });

        jTextFieldMAKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMAKHActionPerformed(evt);
            }
        });
        jTextFieldMAKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMAKHKeyPressed(evt);
            }
        });

        jTextFieldSOPHONG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSOPHONGActionPerformed(evt);
            }
        });
        jTextFieldSOPHONG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSOPHONGKeyPressed(evt);
            }
        });

        jTextFieldNGAYDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNGAYDKActionPerformed(evt);
            }
        });

        jTextFieldNGAYDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNGAYDIActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã ĐK");

        jLabel2.setText("Mã KH");

        jLabel3.setText("Số Phòng");

        jLabel4.setText("Ngày ĐK");

        jLabel5.setText("Ngày Đii");

        jLabel6.setText("Số Ngày");

        jTextFieldSONGAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSONGAYActionPerformed(evt);
            }
        });
        jTextFieldSONGAY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSONGAYKeyTyped(evt);
            }
        });

        them4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/THEM.png"))); // NOI18N
        them4.setText("Thêm");
        them4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them4ActionPerformed(evt);
            }
        });

        sua4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/SUA.png"))); // NOI18N
        sua4.setText("Sửa");
        sua4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua4ActionPerformed(evt);
            }
        });

        jButtonclear4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/CLEAR.png"))); // NOI18N
        jButtonclear4.setText("Clear");
        jButtonclear4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclear4ActionPerformed(evt);
            }
        });

        thoat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/THOAT.png"))); // NOI18N
        thoat4.setText("Thoát");
        thoat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoat4ActionPerformed(evt);
            }
        });

        xoa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/XOA.png"))); // NOI18N
        xoa4.setText("Xóa");
        xoa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSONGAY, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jTextFieldNGAYDK)
                            .addComponent(jTextFieldSOPHONG, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldMAKH, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldMADK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNGAYDI)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(xoa4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(them4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sua4)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonclear4))
                            .addComponent(thoat4))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMADK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMAKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSOPHONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNGAYDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNGAYDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSONGAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sua4)
                    .addComponent(them4)
                    .addComponent(jButtonclear4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xoa4)
                    .addComponent(thoat4))
                .addContainerGap())
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/thuephong.png"))); // NOI18N
        jLabel22.setText("QUẢN LÝ THUÊ PHÒNG");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/Form/hinh/datphong.png"))); // NOI18N
        jButton4.setText("ĐẶT PHÒNG");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addGap(286, 286, 286)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton4)))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();
            String sql = "update hr.thuephong\n"
                    + "set songay=TO_NUMBER(floor(ngaydi - ngaydk))";
            System.out.print(sql);
            // Thưc thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);
            if (rs != null) {
                System.out.println();
                System.out.println("=> thành công");
            }

        } catch (Exception ex) {
            System.out.println();
            System.out.println("=> không thành công");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String colTieuDe1[] = new String[]{"Mã Đăng Kí", "Mã Khách", "Số Phòng", "Ngày Đăng Kí", "Ngày Đi", "Số Ngày"};
        String sql = "select * from hr.thuephong";
        ArrayList<thuephong> dsp = layDanhSachTP(sql);

        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dsp.size(); i++) {

            row = new Object[6];

            // GÁN GIÁ TRỊ
            row[0] = dsp.get(i).getMADK();
            row[1] = dsp.get(i).getMAKH();
            row[2] = dsp.get(i).getSOPHONG();
            row[3] = dsp.get(i).getNGAYDK();
            row[4] = dsp.get(i).getNGAYDI();
            row[5] = dsp.get(i).getSONGAY();
            model.addRow(row);
        }

        //}catch(ArrayIndexOutOfBoundsException ex){
        jTableTHUEPHONG.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldMADKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMADKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMADKActionPerformed

    private void jTextFieldMAKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMAKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMAKHActionPerformed

    private void jTextFieldSOPHONGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSOPHONGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSOPHONGActionPerformed

    private void jTextFieldNGAYDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNGAYDKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNGAYDKActionPerformed

    private void jTextFieldNGAYDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNGAYDIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNGAYDIActionPerformed

    private void jTextFieldSONGAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSONGAYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSONGAYActionPerformed
    public Boolean kiemtratxt() {
        if (jTextFieldMADK.getText().equals("") || jTextFieldMAKH.getText().equals("") || jTextFieldSOPHONG.getText().equals("")
                || jTextFieldSONGAY.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui long nhap day du thong tin", "Thong bao", 2);
            return false;
        }
        return true;
    }

    public Boolean kiemtrangaydi() {
        try {
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            Date date = df.parse(jTextFieldNGAYDI.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập kiểu dữ liệu ngày đi là dd/mm/yyyy", "Thong bao", 2);
            return false;
        }
        return true;
    }

    public Boolean kiemtrangaydk() {
        try {
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            Date date = df.parse(jTextFieldNGAYDK.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập kiểu dữ liệu ngày đăng kí là dd/mm/yyyy", "Thong bao", 2);
            return false;
        }
        return true;
    }
    ArrayList<thuephong> d = layDanhSachTP("select * from hr.thuephong");
    public static Boolean kiemtramadk(ArrayList<thuephong> d, String madk) {
        for (thuephong t : d) {
            if (t.getMADK().equals(madk)) {
                return true;
            }
        }
        return false;
    }

     public Boolean kiemtramadkphong() {
        if (kiemtramadk(d, jTextFieldMADK.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Mã Đăng Ký phòng Khác!!", "Thong bao", 2);
            return false;
        }
        return true;
    }
    
    
    private void them4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them4ActionPerformed
        // TODO add your handling code here:
        if (kiemtratxt() && kiemtrangaydi() && kiemtrangaydk()&&kiemtramadkphong()&&kiemtrasophong()&&kiemtrakhachhang()) {
            Connection con = getConnection(Hostname,Port,SID,Username,Password);
            try {
                // Tạo một đối tượng để thực hiện công việc
                st = (Statement) con.createStatement();
                String query = "INSERT INTO hr.thuephong VALUES('" + jTextFieldMADK.getText() + "',"
                        + "'" + jTextFieldMAKH.getText() + "','" + jTextFieldSOPHONG.getText() + "',TO_DATE('" + jTextFieldNGAYDK.getText()
                        + "','DD/MM/YYYY'),TO_DATE('" + jTextFieldNGAYDI.getText() + "','DD/MM/YYYY')," + jTextFieldSONGAY.getText() + ")";

                System.out.print(query);
                st.execute(query);
                hienThiDanhSachTP();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_them4ActionPerformed
    public ArrayList<Phong> layDanhSachPhong(String sql) {
        ArrayList<Phong> dsp = new ArrayList<Phong>();
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();

            // Thưcj thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            Phong p;
            while (rs.next()) {
                p = new Phong(rs.getString("SOPHONG"), rs.getString("LOAIPHONG"), rs.getInt("GIAPHONG"), rs.getString("TINHTRANG"));

                //Thêm vào danh sách
                dsp.add(p);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        return dsp;
    }
    ArrayList<Phong> dsp = layDanhSachPhong("select * from hr.phong");
    public static Boolean kiemtrasp(ArrayList<Phong> dsp, String sp) {
        for (Phong t : dsp) {
            if (t.getSOPHONG().equals(sp)) {
                return true;
            }
        }
        return false;
    }
    public Boolean kiemtrasophong() {
        if (kiemtrasp(dsp, jTextFieldSOPHONG.getText().trim())) {
            return true;
        }
        else{
            JOptionPane.showMessageDialog(this, "Số Phòng không tồn tại!!", "Thong bao", 2);
        return false;}
    }
    public ArrayList<KhachHang> layDanhSachKhachHang(String sql) {
        ArrayList<KhachHang> dskh = new ArrayList<KhachHang>();
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();

            // Thưcj thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            KhachHang kh;
            while (rs.next()) {
                kh = new KhachHang(rs.getString("MAKH"), rs.getString("TENKH"), rs.getDate("NGAYSINH"), rs.getString("GIOITINH"), rs.getString("CMND"), rs.getString("QUOCTICH"), rs.getString("SDT"), rs.getString("LOAIKH"));

                //Thêm vào danh sách
                dskh.add(kh);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        return dskh;
    }
    ArrayList<KhachHang> dskh = layDanhSachKhachHang("select * from hr.khachhang");
    public static Boolean kiemtrakh(ArrayList<KhachHang> dskh, String makh) {
        for (KhachHang t : dskh) {
            if (t.getMAKH().equals(makh)) {
                return true;
            }
        }
        return false;
    }
    public Boolean kiemtrakhachhang() {
        if (kiemtrakh(dskh, jTextFieldMAKH.getText().trim())) {
            return true;
        }
        else{
            JOptionPane.showMessageDialog(this, "Mã Khách không tồn tại!!", "Thong bao", 2);
        return false;}
    }
    private void sua4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua4ActionPerformed
        // TODO add your handling code here:
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        int pos = jTableTHUEPHONG.getSelectedRow();
        if (pos < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn Hãy Chọn 1 dòng");
        } else {
            try {
                if (kiemtratxt()&&kiemtrasophong()&&kiemtrakhachhang()) {
                    // Tạo một đối tượng để thực hiện công việc
                    int i = -1;
                    st = (Statement) con.createStatement();
                    String query = "update hr.thuephong set sophong='" + jTextFieldSOPHONG.getText()
                            + "', ngaydk=TO_DATE('" + jTextFieldNGAYDK.getText() + "','YYYY/MM/DD'), makh='"
                            + jTextFieldMAKH.getText() + "', ngaydi=TO_DATE('" + jTextFieldNGAYDI.getText() 
                            + "','YYYY/MM/DD'), songay=" + jTextFieldSONGAY.getText()
                            + " where MADK ='" + jTextFieldMADK.getText() + "'";
                    System.out.print(query);
                    i = st.executeUpdate(query);
                    if (i != -1) {
                        hienThiDanhSachTP();
                    }
                }

            } catch (Exception ex) {

                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_sua4ActionPerformed

    private void jButtonclear4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclear4ActionPerformed
        // TODO add your handling code here:
        jTextFieldMADK.setText("");
        jTextFieldSOPHONG.setText("");
        jTextFieldMAKH.setText("");
        jTextFieldNGAYDI.setText("");
        jTextFieldNGAYDK.setText("");
        jTextFieldSONGAY.setText("");
        jTextFieldMADK.requestFocus();
        hienThiDanhSachTP();
    }//GEN-LAST:event_jButtonclear4ActionPerformed

    private void thoat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoat4ActionPerformed
        // TODO add your handling code here:
        thoat4.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát chương"
                + " trình không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_thoat4ActionPerformed

    public ArrayList<CThoadon> layDanhSachCTHD(String sql) {
        ArrayList<CThoadon> dsct = new ArrayList<CThoadon>();
        Connection con = getConnection(Hostname,Port,SID,Username,Password);
        try {
            st = (Statement) con.createStatement();

            // Thưcj thi câu lệnh truy vấn
            ResultSet rs = st.executeQuery(sql);

            CThoadon ct;
            while (rs.next()) {
                ct = new CThoadon(rs.getString("MAHD"), rs.getString("MADK"), rs.getInt("TONGTIEN"), rs.getString("GHICHU"));

                //Thêm vào danh sách
                dsct.add(ct);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        return dsct;
    }
    ArrayList<CThoadon> dsct = layDanhSachCTHD("select * from hr.cthoadon");
    public static Boolean kiemtratt(ArrayList<CThoadon> dsct,String MADK) {
        for (CThoadon c : dsct) {
            if (c.getMADK().equals(MADK)) {
                return true;
            }
        }
        return false;
    }
    public Boolean kiemtrathanhtoan() {
        if (kiemtratt(dsct, jTextFieldMADK.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Vui lòng Thanh Toán rồi hãy Xóa!!", "Thong bao", 2);
            return true;
        }
        return false;
    }
    private void xoa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoa4ActionPerformed
        // TODO add your handling code here:
        int pos = jTableTHUEPHONG.getSelectedRow();
        if (pos < 0) {
            JOptionPane.showMessageDialog(rootPane, "Bạn Hãy Chọn 1 dòng");
        } else {
            Connection con = getConnection(Hostname, Port, SID, Username, Password);
            if (kiemtrathanhtoan() == false) {
                try {

                    // Tạo một đối tượng để thực hiện công việc
                    st = (Statement) con.createStatement();
                    String query = "DELETE FROM hr.thuephong WHERE madk = '" + jTextFieldMADK.getText() + "'";
                    st.executeUpdate(query);
                    hienThiDanhSachTP();

                } catch (Exception ex) {

                    //ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_xoa4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DatPhong_Form frm = new DatPhong_Form();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldSONGAYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSONGAYKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSONGAYKeyTyped

    private void jTableTHUEPHONGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTHUEPHONGMouseClicked
        // TODO add your handling code here:
        int i = jTableTHUEPHONG.getSelectedRow();
        TableModel model = jTableTHUEPHONG.getModel();
        jTextFieldMADK.setText(model.getValueAt(i, 0).toString());
        jTextFieldMAKH.setText(model.getValueAt(i, 1).toString());
        jTextFieldSOPHONG.setText(model.getValueAt(i, 2).toString());
        try {
            jTextFieldNGAYDI.setText(model.getValueAt(i, 4).toString());
        } catch (Exception e) {
            jTextFieldNGAYDI.setText("");
        }
        try {
            jTextFieldNGAYDK.setText(model.getValueAt(i, 3).toString());
        } catch (Exception e) {
            jTextFieldNGAYDK.setText("");
        }
        jTextFieldSONGAY.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_jTableTHUEPHONGMouseClicked

    private void jTextFieldMADKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMADKKeyPressed
        // TODO add your handling code here:
        if(jTextFieldMADK.getText().length()>=10)
        {
            jTextFieldMADK.setText((jTextFieldMADK.getText().substring(0,9)));
        }
    }//GEN-LAST:event_jTextFieldMADKKeyPressed

    private void jTextFieldMAKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMAKHKeyPressed
        // TODO add your handling code here:
        if(jTextFieldMAKH.getText().length()>=10)
        {
            jTextFieldMAKH.setText((jTextFieldMAKH.getText().substring(0,9)));
        }
    }//GEN-LAST:event_jTextFieldMAKHKeyPressed

    private void jTextFieldSOPHONGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSOPHONGKeyPressed
        // TODO add your handling code here:
        if(jTextFieldSOPHONG.getText().length()>=10)
        {
            jTextFieldSOPHONG.setText((jTextFieldMAKH.getText().substring(0,9)));
        }
    }//GEN-LAST:event_jTextFieldSOPHONGKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLThuePhong_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLThuePhong_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLThuePhong_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLThuePhong_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLThuePhong_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonclear4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTHUEPHONG;
    private javax.swing.JTextField jTextFieldMADK;
    private javax.swing.JTextField jTextFieldMAKH;
    private javax.swing.JTextField jTextFieldNGAYDI;
    private javax.swing.JTextField jTextFieldNGAYDK;
    private javax.swing.JTextField jTextFieldSONGAY;
    private javax.swing.JTextField jTextFieldSOPHONG;
    private javax.swing.JButton sua4;
    private javax.swing.JButton them4;
    private javax.swing.JButton thoat4;
    private javax.swing.JButton xoa4;
    // End of variables declaration//GEN-END:variables
}
